import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdirSync,mkdtempSync,readFileSync,existsSync,readdirSync} from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {parsePromptText,decodePromptBytes} from '../public/prompt-import.js';
import {createWorkbench} from '../src/server.js';
import {mediaMetadata} from '../src/asset-media.js';
import {saveAsset} from '../src/library.js';
const png=readFileSync('public/icon-256.png'),mp4=Buffer.concat([Buffer.from([0,0,0,24]),Buffer.from('ftypisom'),Buffer.alloc(20)]);
function dir(){mkdirSync('work',{recursive:true});return mkdtempSync(path.resolve('work','asset-import-'));}
async function connect(app){const root='http://127.0.0.1:'+app.port,cookie=(await fetch(root)).headers.get('set-cookie').split(';')[0];return {root,cookie,async call(route,b,method){const r=await fetch(root+'/api/'+route,{method:method||(b?'POST':'GET'),headers:{cookie,'Content-Type':'application/json'},body:b?JSON.stringify(b):undefined});return {status:r.status,data:await r.json()};},async upload(bytes,name='素材.png'){const r=await fetch(root+'/api/media/upload?name='+encodeURIComponent(name),{method:'POST',headers:{cookie,'Content-Type':'application/octet-stream'},body:bytes});return {status:r.status,data:await r.json()};}};}
test('TXT标记识别、完整参数保留与纯文本不猜测；JSON与编码兼容',()=>{const raw='标题：空间案例\n主题：酒店, 自然光\n正向提示词：木材与光线\n保留动线\n负向提示词：模糊\nSteps: 24, Sampler: Euler, Model: example';const p=parsePromptText(raw,'例子.txt');assert.equal(p.title,'空间案例');assert.equal(p.content,'木材与光线\n保留动线');assert.equal(p.negative,'模糊');assert.equal(p.tags,'酒店, 自然光');assert.equal(p.modelHint,'example');assert.ok(p.note.includes('Steps: 24'));assert.equal(p.raw,raw);const plain=parsePromptText('3:4竖向画幅，木材与采光');assert.equal(plain.content,'3:4竖向画幅，木材与采光');assert.equal(plain.negative,'');assert.equal(plain.tags,'');assert.ok(plain.warnings.some(w=>w.includes('纯文本')));const j=parsePromptText('{"positive":"正文","negative":"负向","tags":["主题"],"未知":{"a":1}}');assert.equal(j.content,'正文');assert.ok(j.note.includes('未知'));assert.equal(decodePromptBytes(Buffer.from([255,254,...Buffer.from('正向：光线','utf16le')])).text,'正向：光线');assert.throws(()=>parsePromptText(' '));assert.throws(()=>decodePromptBytes(Buffer.from('x\0')));});
test('素材签名拒绝HTML/SVG伪装、会话保护、取消上传清理，不写资产',async()=>{const app=await createWorkbench({port:0,dataDir:dir()});try{const c=await connect(app);assert.equal((await c.upload(Buffer.from('<svg onload="x"/>'),'fake.png')).status,400);assert.equal(app.store.list('assets').length,0);const uploaded=await c.upload(png);assert.equal(uploaded.status,200);assert.equal(app.store.list('assets').length,0);const noSession=await fetch(c.root+'/api/media/upload?name=x',{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:png});assert.equal(noSession.status,401);await c.call('media/staged/'+uploaded.data.uploadId,null,'DELETE');assert.equal(existsSync(app.assetMedia.file(uploaded.data.id)),false);assert.equal(app.store.list('assets').length,0);}finally{await app.close();}});
test('确认保存、同内容去重、关联读取/视频Range、编辑保留/移除、回收站恢复',async()=>{const app=await createWorkbench({port:0,dataDir:dir()});try{const c=await connect(app),image=(await c.upload(png)).data,video=(await c.upload(mp4,'demo.mp4')).data;const r=await c.call('assets',{title:'图文收藏',content:'木材与光线',negative:'模糊',tags:'空间',media:[{uploadId:image.uploadId},{uploadId:video.uploadId}],importInfo:{fileName:'demo.txt',raw:'正向：木材与光线'}});assert.equal(r.status,200);const a=r.data;assert.equal(a.media.length,2);assert.equal(a.media[1].type,'video/mp4');const loaded=await fetch(c.root+'/api/assets/'+a.id+'/media/'+image.id,{headers:{cookie:c.cookie}});assert.equal(loaded.status,200);assert.deepEqual(Buffer.from(await loaded.arrayBuffer()),png);const range=await fetch(c.root+'/api/assets/'+a.id+'/media/'+video.id,{headers:{cookie:c.cookie,range:'bytes=4-11'}});assert.equal(range.status,206);assert.equal(range.headers.get('content-length'),'8');assert.equal(Buffer.from(await range.arrayBuffer()).toString(),'ftypisom');assert.equal((await fetch(c.root+'/api/assets/'+a.id+'/media/'+video.id,{headers:{cookie:c.cookie,range:'bytes=999-'}})).status,416);const unknown=await c.call('assets',{title:'非法链接',content:'正文',media:[{id:image.id}]});assert.equal(unknown.status,400);const edited=await c.call('assets',{...a,title:'已编辑',media:a.media.map(m=>({id:m.id})),expectedUpdatedAt:a.updatedAt});assert.equal(edited.status,200);assert.equal(edited.data.media.length,2);await c.call('assets/manage',{ids:[a.id],action:'trash'});await c.call('trash/manage',{kind:'assets',ids:[a.id],action:'restore'});assert.equal(app.store.get('assets',a.id).media.length,2);const duplicate=(await c.upload(png)).data;assert.equal(duplicate.id,image.id);await c.call('media/staged/'+duplicate.uploadId,null,'DELETE');assert.ok(existsSync(app.assetMedia.file(image.id)));const removed=await c.call('assets',{...edited.data,media:[{id:image.id}],expectedUpdatedAt:app.store.get('assets',a.id).updatedAt});assert.equal(removed.data.media.length,1);assert.ok(existsSync(app.assetMedia.file(video.id)));}finally{await app.close();}});
test('素材包跨库导出/导入、合并恢复，正文相同但素材不同不被静默去重',async()=>{const a=await createWorkbench({port:0,dataDir:dir()}),b=await createWorkbench({port:0,dataDir:dir()});try{const ca=await connect(a),cb=await connect(b),upload=(await ca.upload(png)).data,saved=(await ca.call('assets',{title:'有素材',content:'正文',media:[{uploadId:upload.uploadId}]})).data;const exported=(await ca.call('assets/export',{ids:[saved.id]})).data;assert.equal(exported.mediaFiles.length,1);const imported=await cb.call('assets/import',exported);assert.equal(imported.status,200);const asset=b.store.list('assets')[0];assert.equal(asset.media.length,1);assert.deepEqual(readFileSync(b.assetMedia.file(asset.media[0].id)),png);assert.equal((await cb.call('assets/import',exported)).data.skipped,1);const noMedia={...exported,assets:[{...exported.assets[0],media:[]}],mediaFiles:[]};assert.equal((await cb.call('assets/import',noMedia)).data.imported,1);const full=(await ca.call('export')).data;assert.equal((await cb.call('import',full)).status,200);const broken=structuredClone(exported);broken.mediaFiles[0].base64=Buffer.from('<html>bad</html>').toString('base64');assert.equal((await cb.call('assets/import',broken)).status,400);const missing=structuredClone(exported);missing.assets[0].media[0].id=createHash('sha256').update('missing').digest('hex');assert.equal((await cb.call('assets/import',missing)).status,400);}finally{await a.close();await b.close();}});
test('父素材记录永久删除后备份引用保留；重新上传同一素材后取消不破坏文件',async()=>{const app=await createWorkbench({port:0,dataDir:dir()});try{const c=await connect(app),u=(await c.upload(png)).data,a=(await c.call('assets',{title:'保留备份',content:'正文',media:[{uploadId:u.uploadId}]})).data;await c.call('assets/manage',{ids:[a.id],action:'trash'});await c.call('trash/manage',{kind:'assets',ids:[a.id],action:'purge',confirmation:'永久删除'});const reupload=(await c.upload(png)).data;await c.call('media/staged/'+reupload.uploadId,null,'DELETE');assert.ok(existsSync(app.assetMedia.file(u.id)));assert.deepEqual(readFileSync(app.assetMedia.file(u.id)),png);}finally{await app.close();}});
test('同任务再次收藏添加素材会合并，保留已编辑标题而不丢新增素材',async()=>{const app=await createWorkbench({port:0,dataDir:dir()});try{const c=await connect(app),j=app.store.put('jobs',{input:'输入',output:'成果',status:'succeeded',createdAt:new Date().toISOString()}),old=(await c.call('assets',{title:'已编辑的标题',content:'成果',resultJobId:j.id})).data,u=(await c.upload(png)).data;const added=(await c.call('assets',{title:'再次收藏',content:'成果',resultJobId:j.id,media:[{uploadId:u.uploadId}]})).data;assert.equal(added.id,old.id);assert.equal(added.title,old.title);assert.equal(added.media[0].id,u.id);assert.equal(app.store.list('assets').length,1);}finally{await app.close();}});
test('失败的整批素材导入不污染任何历史备份，图片/总量限额不能从JSON绕过',async()=>{const app=await createWorkbench({port:0,dataDir:dir()});try{const c=await connect(app),id=createHash('sha256').update(png).digest('hex'),m={id,type:'image/png',bytes:png.length,name:'test.png'};const bad={schema:'prompt-workbench/assets/v1',mediaFiles:[{id,base64:png.toString('base64')}],assets:[{title:'第一条',content:'正文',media:[m]},{title:'第二条',content:'正文',media:[]},{title:'第三条',content:'',media:[]}]};assert.equal((await c.call('assets/import',bad)).status,400);assert.equal(app.store.list('assets').length,0);assert.equal(existsSync(app.assetMedia.file(id)),false);for(const file of readdirSync(path.join(app.store.dir,'backups')))if(file.endsWith('.json'))assert.equal(JSON.parse(readFileSync(path.join(app.store.dir,'backups',file))).assets.length,0);assert.throws(()=>mediaMetadata([{...m,bytes:20*1024*1024+1}]));assert.throws(()=>mediaMetadata(Array.from({length:3},()=>({...m,type:'video/mp4',bytes:80*1024*1024}))));const large=Buffer.alloc(20*1024*1024+1);png.copy(large);const largeId=createHash('sha256').update(large).digest('hex');assert.throws(()=>app.assetMedia.importFiles([{id:largeId,base64:large.toString('base64')}]));assert.equal(existsSync(app.assetMedia.file(largeId)),false);}finally{await app.close();}});
test('素材与资产跨服务重启保持，GET仍能读回原始字节',async()=>{const dataDir=dir();let app=await createWorkbench({port:0,dataDir});let id,assetId;try{const c=await connect(app),u=(await c.upload(png)).data,a=(await c.call('assets',{title:'重启保留',content:'正文',media:[{uploadId:u.uploadId}]})).data;id=u.id;assetId=a.id;await app.close();app=await createWorkbench({port:0,dataDir});const r=await connect(app),response=await fetch(r.root+'/api/assets/'+assetId+'/media/'+id,{headers:{cookie:r.cookie}});assert.deepEqual(Buffer.from(await response.arrayBuffer()),png);assert.equal(app.store.get('assets',assetId).media[0].id,id);}finally{await app.close();}});
test('重复收藏合并后的总量仍受200MB限制，超限不修改旧资产',async()=>{const app=await createWorkbench({port:0,dataDir:dir()});try{const j=app.store.put('jobs',{status:'succeeded',output:'成果'}),fake=(char)=>({id:char.repeat(64),name:'仅用于元数据限额测试.mp4',type:'video/mp4',bytes:100*1024*1024}),old=saveAsset(app.store,{title:'已存',content:'成果',resultJobId:j.id},{mediaSelection:[fake('a'),fake('b')]});const before=JSON.stringify(old);assert.throws(()=>saveAsset(app.store,{title:'再次收藏',content:'成果',resultJobId:j.id},{mediaSelection:[fake('c')]}),/200MB/);assert.equal(JSON.stringify(app.store.get('assets',old.id)),before);}finally{await app.close();}});
