import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdirSync,mkdtempSync} from 'node:fs';
import path from 'node:path';
import {Store} from '../src/store.js';
import {Jobs} from '../src/jobs.js';
import {checkQuality} from '../src/quality.js';
import {saveSnippet,composeInput,compareJobs} from '../src/prompt-lab.js';
import {manageTrash} from '../src/trash.js';
import {createWorkbench} from '../src/server.js';
import {PromptLab} from '../public/lab.js';
function store(){mkdirSync('work',{recursive:true});return new Store(mkdtempSync(path.resolve('work','lab-test-')));}
function jobs(s,generator=async()=>({output:'自然光，保留动线'})){s.put('providers',{id:'mock',name:'模拟服务',protocol:'openai',baseUrl:'http://127.0.0.1:9999/v1',model:'test'});return new Jobs(s,{open:async()=>''},{withModel:async(p,run)=>run()},{generator});}
const input={input:'保留自然光和动线',providerId:'mock',templateId:'optimize'};
test('检查显示只输出转义文本，不把不可信计数或标签插入HTML',()=>{const lab=new PromptLab({});const html=lab.qualityMarkup({total:1,passed:'<img src="/icon.svg">',length:'<b>假字数</b>',items:[{label:'<script>注入</script>',pass:false}]});assert.ok(!html.includes('<img'));assert.ok(!html.includes('<script>'));assert.ok(html.includes('&lt;img'));});
async function finish(j){for(let i=0;i<100;i++){if(!j.active&&!j.queue.length)return;await new Promise(r=>setTimeout(r,10));}throw Error('模拟任务超时');}
test('本地规则检查：Unicode长度、全词必含、禁含、严格JSON与非法规则',()=>{
  const r=checkQuality('自然光😀',{include:['自然光','动线'],exclude:['模糊'],minLength:4,maxLength:4});assert.equal(r.length,4);assert.equal(r.passed,4);assert.equal(r.pass,false);assert.equal(checkQuality('```json\n{}\n```',{json:true}).pass,false);assert.equal(checkQuality('null',{json:true}).pass,true);assert.equal(checkQuality('内容').pass,null);assert.throws(()=>checkQuality('x',{include:['']}));assert.throws(()=>checkQuality('x',{minLength:4,maxLength:3}));assert.throws(()=>checkQuality('x',{include:['x'.repeat(201)]}));
});
test('片段创建/冲突、原文组合、快照、软删除恢复与跨库备份',()=>{const a=store(),b=store();try{const s=saveSnippet(a,{name:'角色',content:'{{input}} <script>alert(1)</script>'});assert.throws(()=>saveSnippet(a,{name:'角色',content:'重复'}));const newer=saveSnippet(a,{...s,content:'字面 {{input}}',expectedUpdatedAt:s.updatedAt});assert.throws(()=>saveSnippet(a,{...s,content:'旧表单',expectedUpdatedAt:s.updatedAt}));const c=composeInput(a,'原文',[s.id,s.id]);assert.equal(c.snippets.length,1);assert.equal(c.text,'原文\n\n【角色】\n字面 {{input}}');a.put('snippets',{...newer,deletedAt:new Date().toISOString()});assert.throws(()=>composeInput(a,'输入',[s.id]));manageTrash(a,{kind:'snippets',ids:[s.id],action:'restore'});assert.equal(a.get('snippets',s.id).content,newer.content);b.import(a.export());assert.equal(b.get('snippets',s.id).content,newer.content);const invalid=a.export();invalid.snippets.push({id:'bad',name:'',content:'x'});assert.throws(()=>b.import(invalid));}finally{a.close();b.close();}});
test('迭代保存父结果、根需求、固定指令和模板版本；删除父任务后子快照仍在',async()=>{const s=store(),j=jobs(s);try{const p=j.enqueue(input);await finish(j);const parent=s.get('jobs',p.id),before=JSON.stringify(parent);s.put('templates',{...s.get('templates','optimize'),system:'已变更的系统指令',revision:9});const child=j.enqueue({...input,parentJobId:p.id,instruction:'减少重复',qualityRules:{include:['自然光']}});await finish(j);const c=s.get('jobs',child.id);assert.equal(c.status,'succeeded');assert.equal(c.chainId,p.id);assert.equal(c.rootInput,input.input);assert.equal(c.compiled.system,parent.compiled.system);assert.equal(c.templateRevision,parent.templateRevision);assert.equal(c.quality.pass,true);assert.equal(JSON.stringify(s.get('jobs',p.id)),before);s.put('jobs',{...parent,deletedAt:new Date().toISOString()});manageTrash(s,{kind:'jobs',ids:[p.id],action:'purge',confirmation:'永久删除'});assert.equal(s.get('jobs',c.id).parentSnapshot.output,parent.output);assert.throws(()=>j.prepare({...input,parentJobId:p.id,instruction:'再次'}));const progress=j.progress(c.id);assert.ok(!('parentSnapshot' in progress));assert.ok(!('rootInput' in progress));}finally{await j.shutdown();s.close();}});
test('片段进入实际编译指令且冻结，重试/还原不重复追加',async()=>{const s=store(),j=jobs(s);try{const sn=saveSnippet(s,{name:'格式',content:'只输出JSON'}),p=j.enqueue({...input,snippetIds:[sn.id]});await finish(j);const saved=s.get('jobs',p.id);assert.ok(saved.compiled.user.includes('只输出JSON'));assert.equal(saved.rawInput,input.input);saveSnippet(s,{...sn,content:'新版格式'});assert.equal(saved.snippets[0].content,'只输出JSON');const retry=j.prepare(saved);assert.equal(retry.input,saved.input);assert.equal(retry.input.split('只输出JSON').length,2);assert.throws(()=>composeInput(s,'x'.repeat(60000),[sn.id]));}finally{await j.shutdown();s.close();}});
test('迭代失败/取消不产生成功版，不自动重发；拒绝失败父任务',async()=>{const s=store();let calls=0;const j=jobs(s,async(p,b,signal)=>{calls++;if(calls===1)return {output:'上一版'};await new Promise((r,reject)=>signal.addEventListener('abort',()=>reject(Error('cancel')),{once:true}));});try{const p=j.enqueue(input);await finish(j);const child=j.enqueue({...input,parentJobId:p.id,instruction:'修改'});await new Promise(r=>setTimeout(r,10));j.cancel(child.id);await finish(j);assert.equal(s.get('jobs',child.id).status,'cancelled');assert.equal(calls,2);assert.equal(s.get('jobs',p.id).output,'上一版');assert.throws(()=>j.prepare({...input,parentJobId:child.id,instruction:'修改'}));}finally{await j.shutdown();s.close();}});
test('对比条件核对和跨250条历史，不从相同根需求推断同条件',()=>{const s=store();try{const base={input:'原始',variables:{language:'中文'},images:[],compiled:{system:'规则',user:'输入'},status:'succeeded',output:'结果',createdAt:new Date().toISOString()};const a=s.put('jobs',{...base,id:'old-left'});for(let i=0;i<260;i++)s.put('jobs',{...base,id:'other-'+i});const b=s.put('jobs',{...base,id:'right'});assert.equal(compareJobs(s,a.id,b.id).controlled,true);s.put('jobs',{...b,parentJobId:a.id,chainId:a.id,compiled:{system:'规则',user:'新一轮修订'}});const r=compareJobs(s,a.id,b.id);assert.equal(r.related,true);assert.equal(r.controlled,false);assert.equal(r.sameInstructions,false);assert.throws(()=>compareJobs(s,a.id,a.id));s.put('jobs',{...a,deletedAt:new Date().toISOString()});assert.throws(()=>compareJobs(s,a.id,b.id));}finally{s.close();}});
test('工作台接口：组合/检查/对比不调用生成，片段进入统一回收站与导出',async()=>{const s=store();let calls=0;const app=await createWorkbench({port:0,dataDir:s.dir,store:s,generator:async()=>{calls++;return {output:'结果'};}});try{const root='http://127.0.0.1:'+app.port,cookie=(await fetch(root)).headers.get('set-cookie').split(';')[0];const api=async(route,b,method)=>{const r=await fetch(root+'/api/'+route,{method:method||(b?'POST':'GET'),headers:{cookie,'Content-Type':'application/json'},body:b?JSON.stringify(b):undefined});return {status:r.status,data:await r.json()};};const sn=(await api('snippets',{name:'风格',content:'保持简洁'})).data;assert.equal((await api('compose',{input:'输入',snippetIds:[sn.id]})).status,200);assert.equal((await api('quality/check',{text:'输入',rules:{include:['输入']}})).data.pass,true);assert.equal((await api('compare?left=missing&right=other')).status,400);assert.equal(calls,0);await api('snippets/'+sn.id,null,'DELETE');assert.ok((await api('trash')).data.items.some(r=>r.kind==='snippets'));await api('trash/manage',{kind:'snippets',ids:[sn.id],action:'restore'});assert.equal((await api('export')).data.snippets.length,1);assert.equal((await api('quality/check',{text:'x',rules:{json:'script'}})).status,400);}finally{await app.close();}});
test('预览片段更改拒绝生成；明确重试保留原片段与父快照，不依赖已删除父任务或模板',async()=>{const s=store(),j=jobs(s);try{const sn=saveSnippet(s,{name:'格式',content:'旧版格式'});const composed=composeInput(s,input.input,[sn.id]);saveSnippet(s,{...sn,content:'新版格式'});assert.throws(()=>j.prepare({...input,snippetIds:[sn.id],snippetVersions:{[sn.id]:composed.snippets[0].updatedAt}}),/重新预览/);const p=j.enqueue({...input,snippetIds:[sn.id]});await finish(j);const parent=s.get('jobs',p.id),c=j.enqueue({...input,parentJobId:p.id,instruction:'修订'});await finish(j);const original=s.get('jobs',c.id);s.remove('jobs',p.id);s.remove('templates','optimize');const retried=j.retry(c.id);await finish(j);assert.equal(s.get('jobs',retried.id).status,'succeeded');assert.deepEqual(retried.compiled,original.compiled);assert.deepEqual(retried.parentSnapshot,original.parentSnapshot);s.put('templates',{id:'optimize',system:'新模板',user:'{{input}}'});s.put('jobs',parent);const retryParent=j.retry(parent.id);await finish(j);assert.deepEqual(retryParent.snippets,parent.snippets);assert.equal(retryParent.compiled.user,parent.compiled.user);assert.notEqual(retryParent.id,parent.id);}finally{await j.shutdown();s.close();}});
test('检查不可用不丢失生成正文；备份中的检查HTML不被信任',async()=>{const s=store(),other=store(),long='x'.repeat(2000001),j=jobs(s,async()=>({output:long}));try{const p=j.enqueue(input);await finish(j);const result=s.get('jobs',p.id);assert.equal(result.status,'succeeded');assert.equal(result.output,long);assert.ok(result.quality.error);const exported=s.export();exported.jobs[0].output='自然光';exported.jobs[0].qualityRules={include:['自然光']};exported.jobs[0].quality={total:1,passed:'<img src="/icon.svg">',items:[]};other.import(exported);assert.equal(other.get('jobs',p.id).quality.passed,1);assert.equal(other.get('jobs',p.id).quality.length,3);assert.ok(!JSON.stringify(other.get('jobs',p.id).quality).includes('<img'));}finally{await j.shutdown();s.close();other.close();}});
