import { spawn } from 'node:child_process';
import { mkdirSync,mkdtempSync,writeFileSync,existsSync,readFileSync } from 'node:fs';
import path from 'node:path';
import net from 'node:net';
import assert from 'node:assert/strict';
import { createWorkbench } from '../src/server.js';
import { setTimeout as sleep } from 'node:timers/promises';

mkdirSync('work',{recursive:true});const evidence=path.resolve(process.env.PW_UI_EVIDENCE_DIR||'work/ui-evidence');mkdirSync(evidence,{recursive:true});writeFileSync(evidence+'/ui-result.json',JSON.stringify({status:'RUNNING',realModel:false}));
const dataDir=mkdtempSync(path.resolve('work','ui-'));const profile=mkdtempSync(path.resolve('work','chrome-'));
let uiModel='';const app=await createWorkbench({port:0,dataDir,xFetcher:async()=>new Response(JSON.stringify({code:200,status:{id:'1923016036120658122',text:'Prompt below',author:{screen_name:'artist'},media:{photos:[{url:'https://pbs.twimg.com/media/test.jpg'}]}},thread:[{id:'1923016048791650481',text:'保留材质和光线，形成可复用提示词。',author:{screen_name:'artist'},media:{photos:[]}}]})),imageFetcher:async()=>new Response(readFileSync('public/icon-256.png')),sourceFetcher:async()=>new Response(JSON.stringify({success:true,result:{positive:'保留用户约束，明确任务和输出。',negative:'模糊'}})),generator:async p=>{uiModel=p.model;await sleep(100);return {output:'温暖的精品酒店阅读角，木质墙面与柔和自然采光，清晰的空间动线。',usage:{completion_tokens:32}};}});
app.sources.ingest('shortcut',JSON.stringify([{id:100,zh:{title:'界面验收 · 分享条目',prompt:'保留用户约束，明确任务和输出。',remark:'模拟公开数据'},tags:['write']}]));
app.sources.ingest('mother',JSON.stringify({success:true,result:{total:4,datas:Array.from({length:4},(_,i)=>({id:3000+i,title:'界面验收 · 效果图 '+i,frontCover:'https://img.alicdn.com/mock-'+i+'.png',models:'测试绘图模型',author:{nickname:'测试作者'}}))}}));
for(const row of app.store.list('shared'))if(row.sourceId==='mother')app.store.put('shared',{...row,content:'合成公开界面样例：保留用户约束，明确任务和输出。',negative:'模糊',detailLoaded:true,importedFrom:'local-file'});
// 仅预热由模拟获取器生成的本地图片，受限来源浏览不触发远程下载。
for(const row of app.store.list('shared'))if(row.sourceId==='mother'&&row.coverUrl)await app.imageCache.get(row.coverUrl);
const tmp=net.createServer();await new Promise(r=>tmp.listen(0,'127.0.0.1',r));const debugPort=tmp.address().port;await new Promise(r=>tmp.close(r));
const chrome=['C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(existsSync);if(!chrome)throw new Error('没有可用浏览器');
const child=spawn(chrome,['--headless=new','--disable-gpu','--no-first-run','--no-default-browser-check',`--remote-debugging-port=${debugPort}`,`--user-data-dir=${profile}`,'about:blank'],{windowsHide:true,stdio:'ignore'});
let ws;
try{
  let tabs;for(let i=0;i<60;i++){try{tabs=await (await fetch(`http://127.0.0.1:${debugPort}/json/list`)).json();if(tabs.length)break;}catch{}await sleep(200);}
  if(!tabs)throw new Error('浏览器调试入口启动失败');
  ws=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j;});let seq=0;const pending=new Map(),errors=[];
  ws.onmessage=e=>{const msg=JSON.parse(e.data);if(msg.id){const p=pending.get(msg.id);if(p){pending.delete(msg.id);msg.error?p.reject(new Error(msg.error.message)):p.resolve(msg.result);}}else if(msg.method==='Runtime.exceptionThrown')errors.push(msg.params.exceptionDetails.text+': '+(msg.params.exceptionDetails.exception?.description||''));else if(msg.method==='Page.javascriptDialogOpening')ws.send(JSON.stringify({id:++seq,method:'Page.handleJavaScriptDialog',params:{accept:true,promptText:'界面验收文件夹'}}));};
  const cdp=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));setTimeout(()=>{if(pending.has(id)){pending.delete(id);reject(new Error('CDP 超时 '+method));}},15000).unref();});
  const evaluate=async expression=>{const r=await cdp('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;};
  const wait=async expression=>{for(let i=0;i<100;i++){if(await evaluate(expression))return;await sleep(100);}throw new Error('界面未达到预期：'+expression);};
  await cdp('Runtime.enable');await cdp('Page.enable');await cdp('Emulation.setDeviceMetricsOverride',{width:1440,height:1100,deviceScaleFactor:1,mobile:false});await cdp('Page.navigate',{url:`http://127.0.0.1:${app.port}`});
  await wait('document.querySelectorAll("#template-select option").length>=7');
  assert.equal(await evaluate('document.querySelector("#share-auto").checked'),true,'auto-load enabled by default');
  assert.equal(await evaluate('document.querySelectorAll("nav [data-mode]").length'),0);
  for(const view of ['workspace','library','templates','plaza','inbox','history','recycle','models','settings']){await evaluate(`document.querySelector('[data-view=${view}]').click()`);assert.equal(await evaluate('document.querySelectorAll("nav button.selected").length'),1);assert.equal(await evaluate('!document.querySelector("#batch-open").classList.contains("hidden")'),view==='workspace');assert.equal(await evaluate('document.querySelector("#add-asset").closest("section").id'),'library');}
  await evaluate(`document.querySelector('[data-view=workspace]').click()`);
  const controls=await evaluate('Array.from(document.querySelectorAll("#provider-select,#model-name,#model-refresh,#connection-status,#connection-edit")).map(n=>{const r=n.getBoundingClientRect();return {top:r.top,height:r.height}})');assert.ok(controls.every(r=>Math.abs(r.top-controls[0].top)<2&&Math.abs(r.height-controls[0].height)<2),'model controls aligned '+JSON.stringify(controls));
  // 页面内同源请求，仅配置本地 mock，不发送任何真实用户数据
  await evaluate(`(async()=>{const r=await fetch('/api/providers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'界面验收模型',protocol:'openai',baseUrl:'http://127.0.0.1:9999/v1',model:'mock-ui',apiKey:'fake-test-key'})});const p=await r.json();window.testProvider=p.id;})()`);
  await wait('Array.from(document.querySelectorAll("#provider-select option")).some(o=>o.value===window.testProvider)');
  app.store.put('modelLists',{id:app.store.list('providers').find(p=>p.model==='mock-ui').id,models:[{id:'mock-ui'},{id:'mock-ui-alternate'}]});
  await evaluate(`document.querySelector('#provider-select').value=window.testProvider;document.querySelector('#provider-select').dispatchEvent(new Event('change'));document.querySelector('#input').value='为精品酒店设计阅读角，保留自然采光与动线。';document.querySelector('#input').dispatchEvent(new Event('input'));document.querySelector('#run').click()`);
  await wait('document.querySelector("#output").value.includes("木质墙面")');
  await wait('document.querySelector("#model-name").textContent.includes("mock-ui-alternate")');
  await evaluate(`document.querySelector('#model-name').value='mock-ui-alternate';document.querySelector('#model-name').dispatchEvent(new Event('change'))`);
  await wait('document.querySelector("#model-name").value==="mock-ui-alternate"');await sleep(250);
  await evaluate(`document.querySelector('#run').click()`);await wait('document.querySelector("#run-feedback").textContent.includes("mock-ui-alternate") && !document.querySelector("#run").disabled');assert.equal(uiModel,'mock-ui-alternate');
  await evaluate(`document.querySelector('#save-output').click();document.querySelector('#asset-form [name=title]').value='酒店阅读角';document.querySelector('#asset-form').requestSubmit()`);
  await wait('!document.querySelector("#asset-dialog").open');
  await evaluate(`document.querySelector('[data-view=library]').click()`);await wait('document.querySelector("#assets-list").textContent.includes("酒店阅读角")');
  await evaluate(`document.querySelector('#folder-add').click();document.querySelector('#folder-name').value='界面验收文件夹';document.querySelector('#folder-form').requestSubmit()`);await wait('document.querySelector("#asset-folder").textContent.includes("界面验收文件夹")');await evaluate(`document.querySelector('#folder-dialog [data-close]').click()`);
  await evaluate(`document.querySelector('[data-action=asset-star]').click()`);await wait('document.querySelector(".star-button").textContent==="★"');
  await evaluate(`document.querySelector('#asset-select-all').click();document.querySelector('#asset-trash-selected').click()`);await wait('!document.querySelector("#assets-list").textContent.includes("酒店阅读角")');
  await evaluate(`document.querySelector('#asset-scope').value='trash';document.querySelector('#asset-scope').dispatchEvent(new Event('change'))`);await wait('document.querySelector("#assets-list").textContent.includes("酒店阅读角")');
  await evaluate(`document.querySelector('[data-action=asset-restore]').click()`);await wait('!document.querySelector("#assets-list").textContent.includes("酒店阅读角")');
  await evaluate(`document.querySelector('#asset-scope').value='all';document.querySelector('#asset-scope').dispatchEvent(new Event('change'))`);await wait('document.querySelector("#assets-list").textContent.includes("酒店阅读角")');
  await evaluate(`document.querySelector('[data-view=templates]').click();document.querySelector('#add-template').click();const f=document.querySelector('#template-form');f.elements.namedItem('name').value='界面验收模板';f.elements.namedItem('system').value='保留约束';f.elements.namedItem('user').value='{{input}}';f.requestSubmit()`);
  await wait('document.querySelector("#templates-list").textContent.includes("界面验收模板")');
  const tid=app.store.list('templates').find(t=>t.name==='界面验收模板').id;
  await evaluate(`document.querySelector('[data-action=template-edit][data-id="${tid}"]').click()`);await wait('document.querySelector("#template-dialog").open');await evaluate(`document.querySelector('#variable-add').click();const row=document.querySelector('.variable-definition');row.querySelector('[data-def=key]').value='style';row.querySelector('[data-def=label]').value='风格';row.querySelector('[data-def=default]').value='自然';document.querySelector('#template-form').elements.system.value='保留约束，风格{{style}}';document.querySelector('#template-preview').click()`);await wait('document.querySelector("#template-preview-output").textContent.includes("风格自然")');
  await evaluate(`document.querySelector('#template-form').requestSubmit()`);await wait('!document.querySelector("#template-dialog").open');assert.equal(app.store.get('templates',tid).revision,2);
  assert.equal(app.store.get('templates',tid).variableSchema.length,1);await evaluate(`document.querySelector('[data-action=template-edit][data-id="${tid}"]').click()`);await wait('document.querySelector("#template-dialog").open');await evaluate(`document.querySelector('#template-version-select').value='1';document.querySelector('#template-version-select').dispatchEvent(new Event('change'))`);assert.ok(await evaluate('document.querySelector("#template-comparison").textContent.includes("历史版本")'));await evaluate(`document.querySelector('#template-restore').click()`);await wait('document.querySelector("#template-version-label").textContent.includes("v3")');assert.equal(app.store.get('templates',tid).variableSchema.length,0);await evaluate(`document.querySelector('#template-dialog [data-close]').click()`);
  await evaluate(`document.querySelector('[data-view=inbox]').click();document.querySelector('#inbox-urls').value='https://x.com/artist/status/1923016036120658122';document.querySelector('#inbox-capture').click()`);await wait('document.querySelector("[data-review-inbox]")');await evaluate(`document.querySelector('[data-review-inbox]').click()`);await wait('document.querySelector("#inbox-dialog").open');assert.ok(await evaluate('document.querySelector("#inbox-content").value.includes("保留材质")'));assert.equal(await evaluate('document.querySelector("#inbox-confirm").checked'),false);
  await wait('document.querySelector("#inbox-images img").naturalWidth>0');
  const full=await evaluate('(()=>{const i=document.querySelector("#inbox-list img");return {fit:getComputedStyle(i).objectFit,ratio:i.clientWidth/i.clientHeight,natural:i.naturalWidth/i.naturalHeight};})()');assert.equal(full.fit,'contain');assert.ok(full.natural>0);
  await evaluate(`document.querySelector('#inbox-confirm').checked=true;document.querySelector('#inbox-collect').click()`);await wait('!document.querySelector("#inbox-dialog").open');assert.ok(app.store.list('assets').some(a=>a.source?.url?.endsWith('1923016048791650481')));
  await wait('!document.querySelector("#inbox-capture").disabled');assert.equal(await evaluate('document.querySelector("#inbox-urls").value'),'');await wait('document.querySelector("#inbox-list img").naturalWidth>0');
  await evaluate(`document.querySelector('[data-view=library]').click()`);assert.ok(await evaluate('document.querySelector("#assets-list").textContent.includes("X案例")'));await evaluate(`document.querySelector('#asset-select-all').click();document.querySelector('#asset-bulk-tag').value='收录';document.querySelector('#asset-tag-add').click()`);await wait('document.querySelector("#assets-list").textContent.includes("收录")');await evaluate(`document.querySelector('#asset-tag-filter').value='收录';document.querySelector('#asset-tag-filter').dispatchEvent(new Event('change'));document.querySelector('#asset-select-all').click();document.querySelector('#asset-tag-remove').click()`);await wait('document.querySelector("#asset-tag-filter").value===""');await evaluate(`document.querySelector('[data-view=inbox]').click()`);await wait('document.querySelector("#inbox-list img")');
  await evaluate(`document.querySelector('#inbox-list img').click()`);await wait('document.querySelector("#inbox-dialog").open');await evaluate(`document.querySelector('#inbox-dialog [data-close]').click()`);
  await evaluate(`document.querySelector('#inbox-list img').click()`);await wait('document.querySelector("#inbox-dialog").open');await evaluate(`document.querySelector('#inbox-use').click()`);assert.ok(await evaluate('document.querySelector("#input").value.includes("保留材质")'));await evaluate(`document.querySelector('[data-view=inbox]').click()`);
  for(const id of ['asset','template','provider','batch','share','job','inbox']){await evaluate(`document.querySelector('#${id}-dialog').showModal()`);const closeSize=await evaluate(`document.querySelector('#${id}-dialog [data-close]').getBoundingClientRect().width`);assert.ok(closeSize>=44);await cdp('Input.dispatchMouseEvent',{type:'mousePressed',x:3,y:3,button:'left',clickCount:1});await cdp('Input.dispatchMouseEvent',{type:'mouseReleased',x:3,y:3,button:'left',clickCount:1});assert.equal(await evaluate(`document.querySelector('#${id}-dialog').open`),false);}
  await evaluate(`document.querySelector('#inbox-list label.check').click()`);assert.equal(await evaluate('document.querySelector("#inbox-dialog").open'),false);assert.equal(await evaluate('document.querySelector("[data-inbox-select]").checked'),true);await evaluate(`document.querySelector('#inbox-clear-selection').click()`);
  await evaluate(`document.querySelector('#inbox-all').click();document.querySelector('#inbox-trash').click()`);await wait('!document.querySelector("[data-review-inbox]")');assert.ok(app.store.list('assets').some(a=>a.source?.sourceId==='x-direct'));
  await evaluate(`document.querySelector('#inbox-scope').value='trash';document.querySelector('#inbox-scope').dispatchEvent(new Event('change'));document.querySelector('#inbox-all').click();document.querySelector('#inbox-restore').click()`);await wait('!document.querySelector("[data-review-inbox]")');await evaluate(`document.querySelector('#inbox-scope').value='active';document.querySelector('#inbox-scope').dispatchEvent(new Event('change'))`);await wait('document.querySelector("[data-review-inbox]")');
  await evaluate(`document.querySelector('#inbox-urls').value='https://evil.test/not-a-post';document.querySelector('#inbox-capture').click()`);await wait('document.querySelector("[data-retry-url]")');assert.equal(await evaluate('document.querySelector("#inbox-urls").value'),'https://evil.test/not-a-post');
  await evaluate(`document.querySelector('#inbox-urls').value='https://x.com/artist/status/1923016036120658122';document.querySelector('#inbox-capture').click();document.querySelector('#inbox-urls').value='下一批准备输入的链接'`);await wait('!document.querySelector("#inbox-capture").disabled');assert.equal(await evaluate('document.querySelector("#inbox-urls").value'),'下一批准备输入的链接');
  const originalInbox=app.store.list('inbox')[0];for(const id of ['1923016036120658123','1923016036120658124'])app.store.put('inbox',{...originalInbox,id,url:'https://x.com/artist/status/'+id,posts:originalInbox.posts.map(p=>({...p,id,sourceUrl:'https://x.com/artist/status/'+id})),candidateId:id,selectedPostId:id});
  await evaluate(`document.querySelector('#inbox-refresh').click()`);await wait('document.querySelectorAll(".inbox-card").length===3');const grid=await evaluate('(()=>{const boxes=Array.from(document.querySelectorAll(".inbox-card")).map(n=>n.getBoundingClientRect());return {display:getComputedStyle(document.querySelector("#inbox-list")).display,tops:boxes.map(r=>r.top),widths:boxes.map(r=>r.width),imageHeights:Array.from(document.querySelectorAll(".capture-cover")).map(n=>n.getBoundingClientRect().height)};})()');assert.equal(grid.display,'grid');assert.ok(grid.tops.every(y=>Math.abs(y-grid.tops[0])<2),'three inbox cards in one desktop row');assert.ok(grid.imageHeights.every(h=>h<=360));await sleep(200);writeFileSync(evidence+'/inbox-grid-desktop.png',Buffer.from((await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:true})).data,'base64'));
  await evaluate(`document.querySelector('[data-view=history]').click()`);await wait('document.querySelector("#jobs-list").textContent.includes("已完成")');
  await evaluate(`document.querySelector('#history-select-all').click();document.querySelector('#history-trash-selected').click()`);await wait('!document.querySelector("#jobs-list").textContent.includes("已完成")');
  await evaluate(`document.querySelector('#history-scope').value='trash';document.querySelector('#history-scope').dispatchEvent(new Event('change'))`);await wait('document.querySelector("#jobs-list").textContent.includes("已完成")');
  await evaluate(`document.querySelector('#history-select-all').checked=false;document.querySelector('#history-select-all').click();document.querySelector('#history-restore-selected').click()`);await wait('!document.querySelector("#jobs-list").textContent.includes("已完成")');
  await evaluate(`document.querySelector('#history-scope').value='active';document.querySelector('#history-scope').dispatchEvent(new Event('change'))`);await wait('document.querySelector("#jobs-list").textContent.includes("已完成")');
  await evaluate(`document.querySelector('[data-view=plaza]').click();document.querySelector('#share-source').value='shortcut';document.querySelector('#share-kind').value='text';document.querySelector('#share-kind').dispatchEvent(new Event('change'))`);await wait('document.querySelector("#shared-list").textContent.includes("界面验收 · 分享条目")');
  await evaluate(`document.querySelector('[data-shared-card] h3').click()`);await wait('document.querySelector("#share-dialog").open');assert.ok(await evaluate('document.querySelector("#share-detail").textContent.includes("保留用户约束")'));
  await evaluate(`document.querySelector('#share-dialog [data-close]').click();document.querySelector('[data-action=shared-collect]').click()`);await wait(`(async()=>{const r=await (await fetch('/api/state')).json();return r.assets.some(a=>a.source?.sourceId==='shortcut'&&a.isResult===false);})()`);
  await evaluate(`document.querySelector('#share-source').value='mother';document.querySelector('#share-kind').value='images';document.querySelector('#share-kind').dispatchEvent(new Event('change'))`);await wait('document.querySelectorAll("#shared-list img").length===4');await wait('Array.from(document.querySelectorAll("#shared-list img")).every(n=>n.complete&&n.naturalWidth>0)');
  for(const target of ['img','h3',null]){await evaluate(target?`document.querySelector('[data-shared-card] ${target}').click()`:`document.querySelector('[data-shared-card]').click()`);await wait('document.querySelector("#share-dialog").open');assert.ok(await evaluate('document.querySelector("#share-detail").textContent.includes("负向提示词")'));await evaluate(`document.querySelector('#share-dialog [data-close]').click()`);}
  await evaluate(`document.querySelector('#cache-open').click()`);await wait('document.querySelector("#cache-summary").textContent.includes("5 张图片")');await evaluate(`document.querySelector('#cache-clear').click()`);await wait('document.querySelector("#cache-summary").textContent.includes("0 张图片")');assert.ok(app.store.list('assets').length>0);
  await evaluate(`document.querySelector('#cache-limit').value='64';document.querySelector('#cache-days').value='7';document.querySelector('#cache-save').click()`);await wait('document.querySelector("#cache-summary").textContent.includes("64 MB")');
  await cdp('Page.reload');await wait('document.querySelector("#cache-limit").value==="64" && document.querySelector("#cache-days").value==="7" && !document.querySelector("#cache-save").disabled');
  await evaluate(`window.originalFetch=window.fetch;window.fetch=(url,...args)=>String(url)==='/api/cache'?Promise.reject(new TypeError('Failed to fetch')):window.originalFetch(url,...args);document.querySelector('#cache-refresh').click()`);await wait('document.querySelector("#toast").textContent.includes("无法连接本地工作台")');assert.equal(await evaluate('document.querySelector("#cache-save").disabled'),true);await evaluate(`window.fetch=window.originalFetch;document.querySelector('#cache-refresh').click()`);await wait('!document.querySelector("#cache-save").disabled');
  app.sources.ingest('mother',JSON.stringify({success:true,result:{total:121,datas:Array.from({length:121},(_,i)=>({id:3000+i,title:'分页验收 '+i,frontCover:'https://img.alicdn.com/mock-'+i%4+'.png',models:'测试模型'}))}}));
  await evaluate(`document.querySelector('#share-auto').checked=false`);
  await evaluate(`document.querySelector('[data-view=plaza]').click();document.querySelector('#share-size').value='20';document.querySelector('#share-source').value='mother';document.querySelector('#share-source').dispatchEvent(new Event('change'))`);await wait('document.querySelectorAll("#shared-list [data-shared-card]").length===20');assert.ok(await evaluate('!Array.from(document.querySelectorAll("#share-source option")).some(n=>["xbanana","xgpt"].includes(n.value))'));
  await evaluate(`document.querySelector('#share-next').click()`);await wait('document.querySelector("#share-page").textContent.startsWith("第 2 页")');
  for(const [size,last]of [[50,21],[100,21]]){await evaluate(`document.querySelector('#share-size').value='${size}';document.querySelector('#share-size').dispatchEvent(new Event('change'))`);await wait(`document.querySelectorAll('#shared-list [data-shared-card]').length===${size}`);await evaluate(`document.querySelector('#share-jump').value='999';document.querySelector('#share-go').click()`);await wait(`document.querySelectorAll('#shared-list [data-shared-card]').length===${last} && document.querySelector('#share-next').disabled`);}
  await evaluate(`document.querySelector('#share-size').value='20';document.querySelector('#share-size').dispatchEvent(new Event('change'))`);await wait('document.querySelectorAll("#shared-list [data-shared-card]").length===20');await evaluate(`document.querySelector('#share-auto').checked=true;document.querySelector('#share-auto').dispatchEvent(new Event('change'));window.scrollTo(0,document.documentElement.scrollHeight)`);await wait('document.querySelectorAll("#shared-list [data-shared-card]").length>=40');
  for(const count of [60,80,100,120,121]){await evaluate('window.scrollTo(0,document.documentElement.scrollHeight)');await wait(`document.querySelectorAll('#shared-list [data-shared-card]').length>=${count}`);}await wait('document.querySelector("#share-auto-status").textContent.includes("最后一页")');assert.equal(await evaluate('document.querySelector("#share-load-more").disabled'),true);
  await evaluate(`document.querySelector('#share-auto-toggle').click();document.querySelector('#share-jump').value='1';document.querySelector('#share-go').click()`);await wait('document.querySelectorAll("#shared-list [data-shared-card]").length===20');
  await evaluate(`window.savedFetch=window.fetch;window.fetch=(url,...args)=>String(url).startsWith('/api/shared?')&&String(url).includes('offset=20')?Promise.reject(new TypeError('network offline')):window.savedFetch(url,...args);document.querySelector('#share-auto').checked=true;document.querySelector('#share-auto').dispatchEvent(new Event('change'));window.scrollTo(0,document.documentElement.scrollHeight)`);await wait('!document.querySelector("#share-auto").checked && document.querySelector("#share-auto-status").textContent.includes("暂停") && document.querySelector("#share-auto-toggle").textContent.includes("开启")');assert.equal(await evaluate('document.querySelectorAll("#shared-list [data-shared-card]").length'),20);await evaluate('window.fetch=window.savedFetch');
  await evaluate(`document.querySelector('[data-view=plaza]').click()`);await sleep(300);const plaza=await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});writeFileSync(evidence+'/plaza-desktop.png',Buffer.from(plaza.data,'base64'));
  await evaluate(`document.querySelector('[data-view=library]').click()`);await sleep(200);const assets=await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});writeFileSync(evidence+'/library-desktop.png',Buffer.from(assets.data,'base64'));
  await evaluate(`Array.from(document.querySelectorAll('.asset-card')).find(n=>n.textContent.includes('酒店阅读角')).querySelector('[data-action=asset-duplicate]').click()`);await wait('document.querySelector("#asset-dialog").open');
  await evaluate(`document.querySelector('#asset-form').requestSubmit()`);await wait('!document.querySelector("#asset-dialog").open');assert.ok(app.store.list('assets').filter(a=>a.title.includes('酒店阅读角')).length===2);assert.equal(await evaluate('document.querySelector("#assets-list").textContent.includes("界面验收 · 分享条目")'),true);
  await evaluate(`document.querySelector('[data-view=workspace]').click()`);await sleep(300);const screen=await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});writeFileSync(evidence+'/workspace-desktop.png',Buffer.from(screen.data,'base64'));
  let releaseRunning;app.jobs.generator=()=>new Promise(resolve=>{releaseRunning=()=>resolve({output:'新的模拟成果'});});await evaluate(`document.querySelector('#run').click()`);await wait('document.querySelector("#run").disabled');await evaluate(`document.querySelector('[data-view=inbox]').click()`);await wait('document.querySelector("[data-review-inbox]")');await evaluate(`document.querySelector('[data-review-inbox]').click()`);await wait('document.querySelector("#inbox-dialog").open');await evaluate(`document.querySelector('#inbox-use').click()`);await wait('document.querySelector("#toast").textContent.includes("正在运行")');assert.equal(await evaluate('document.querySelector("#inbox-dialog").open'),true);assert.ok(app.jobs.active);for(let n=0;n<100&&!releaseRunning;n++)await sleep(30);releaseRunning();await wait('!document.querySelector("#run").disabled');await evaluate(`document.querySelector('#inbox-dialog [data-close]').click()`);
  const completed=app.store.list('jobs').find(j=>j.output==='新的模拟成果');await evaluate(`document.querySelector('[data-view=history]').click()`);await wait(`document.querySelector('[data-action=job-use][data-id="${completed.id}"]')`);await evaluate(`document.querySelector('[data-action=job-use][data-id="${completed.id}"]').click()`);await wait('document.querySelector("#output").value==="新的模拟成果"');await evaluate(`document.querySelector('#save-output').click();document.querySelector('#asset-form [name=title]').value='历史成果再保存';document.querySelector('#asset-form').requestSubmit()`);await wait('!document.querySelector("#asset-dialog").open');assert.equal(app.store.list('assets').find(a=>a.title==='历史成果再保存').resultJobId,completed.id);

  // 0.3.4 lifecycle: template trash / restore / purge; incremental output before completion.
  const recycleTemplate=app.store.put('templates',{name:'回收站界面验收',category:'测试',system:'保留约束',user:'{{input}}'});
  await evaluate(`document.querySelector('[data-view=templates]').click()`);await wait(`document.querySelector('[data-action=template-delete][data-id="${recycleTemplate.id}"]')`);await evaluate(`document.querySelector('[data-action=template-delete][data-id="${recycleTemplate.id}"]').click()`);await wait(`(async()=>!(await(await fetch('/api/state')).json()).templates.some(t=>t.id==='${recycleTemplate.id}'))()`);
  await evaluate(`document.querySelector('[data-view=recycle]').click();document.querySelector('#trash-kind').value='templates';document.querySelector('#trash-kind').dispatchEvent(new Event('change'));document.querySelector('#trash-refresh').click()`);await wait('document.querySelector("#trash-list").textContent.includes("回收站界面验收")');await evaluate(`document.querySelector('#trash-all').click();document.querySelector('#trash-restore').click()`);await wait('document.querySelector("#trash-list .empty")');assert.equal(app.store.get('templates',recycleTemplate.id).deletedAt,null);assert.equal(await evaluate('document.querySelector("#trash-restore").disabled'),true);
  app.store.put('templates',{...app.store.get('templates',recycleTemplate.id),deletedAt:new Date().toISOString()});await evaluate(`document.querySelector('#trash-refresh').click()`);await wait('document.querySelector("#trash-list").textContent.includes("回收站界面验收")');await evaluate(`document.querySelector('#trash-all').click();document.querySelector('#trash-purge').click()`);await wait('document.querySelector("#confirm-dialog").open');assert.equal(await evaluate('document.querySelector("#confirm-dialog input")'),null);await evaluate(`document.querySelector('#confirm-dialog [data-confirm-accept]').click()`);await wait('document.querySelector("#trash-list .empty")');assert.equal(app.store.get('templates',recycleTemplate.id),null);writeFileSync(evidence+'/recycle-desktop.png',Buffer.from((await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:true})).data,'base64'));
  await evaluate(`document.querySelector('[data-view=settings]').click();document.querySelector('#database-refresh').click()`);await wait('document.querySelector("#database-summary").textContent.includes("数据检查正常")');
  let endStream;app.jobs.generator=async(p,input)=>{input.onProgress('实时出现的正文');await new Promise(r=>endStream=r);return {output:'实时出现的正文，完整结束。'};};await evaluate(`document.querySelector('[data-view=workspace]').click();document.querySelector('#run').click()`);await wait('document.querySelector("#output").value==="实时出现的正文"');assert.equal(await evaluate('document.querySelector("#output").readOnly'),true);assert.equal(await evaluate('document.querySelector("#save-output").disabled'),true);assert.ok(app.jobs.active);writeFileSync(evidence+'/stream-desktop.png',Buffer.from((await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:true})).data,'base64'));endStream();await wait('document.querySelector("#output").value.includes("完整结束")&&!document.querySelector("#run").disabled');
  await evaluate(`document.querySelector('#theme').click()`);writeFileSync(evidence+'/workspace-dark.png',Buffer.from((await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:true})).data,'base64'));await evaluate(`document.querySelector('#theme').click()`);
  assert.equal(await evaluate('document.documentElement.scrollWidth<=window.innerWidth'),true,'desktop overflow');

  await cdp('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await sleep(300);assert.equal(await evaluate('document.documentElement.scrollWidth<=window.innerWidth'),true,'mobile overflow');assert.ok(await evaluate('document.querySelector("#model-name").getBoundingClientRect().width>300'),'mobile model picker width');const mobile=await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});writeFileSync(evidence+'/workspace-mobile.png',Buffer.from(mobile.data,'base64'));
  for(const view of ['library','templates','inbox','plaza','history','recycle','models','settings']){await evaluate(`document.querySelector('[data-view=${view}]').click()`);await sleep(120);assert.equal(await evaluate('document.documentElement.scrollWidth<=window.innerWidth'),true,view+' mobile overflow');}

  const oldCurrent=app.store.list('jobs').find(j=>j.output==='实时出现的正文，完整结束。');await evaluate(`window.detailReads=0;window.preEvictionFetch=window.fetch;window.fetch=(url,...args)=>{if(String(url)==='/api/jobs/${oldCurrent.id}')window.detailReads++;return window.preEvictionFetch(url,...args);};`);
  for(let n=0;n<260;n++)app.store.put('jobs',{id:'eviction-'+n,status:'succeeded',input:'分页挤出测试',output:'模拟结果',createdAt:new Date().toISOString()});await wait('window.detailReads>0');await evaluate(`window.fetch=window.preEvictionFetch;document.querySelector('#asset-search').dispatchEvent(new Event('input'));`);
  app.jobs.generator=async()=>({output:'批量模拟结果'});
  // Two keyboard submits must enqueue a single batch.
  await evaluate(`document.querySelector('[data-view=workspace]').click();document.querySelector('#batch-open').click();document.querySelector('#batch-form [name=inputs]').value='第一条\\n---\\n第二条';document.querySelector('#batch-form').requestSubmit();document.querySelector('#batch-form').requestSubmit()`);await wait('!document.querySelector("#batch-dialog").open');await wait('(async()=>{const s=await(await fetch("/api/state")).json();return !s.activeJobId&&s.jobs.filter(j=>j.input==="第一条"||j.input==="第二条").every(j=>j.status==="succeeded");})()');assert.equal(app.store.list('jobs').filter(j=>['第一条','第二条'].includes(j.input)).length,2);

  // Complete folder management, independent of the current folder filter.
  await cdp('Emulation.setDeviceMetricsOverride',{width:1440,height:1100,deviceScaleFactor:1,mobile:false});await evaluate(`document.querySelector('[data-view=library]').click();document.querySelector('#asset-folder').value='unfiled';document.querySelector('#folder-manage').click();document.querySelector('#folder-new').click();document.querySelector('#folder-name').value='工作归档';document.querySelector('#folder-form').requestSubmit()`);await wait('document.querySelector("#folder-list").textContent.includes("工作归档")');const folder=app.store.list('folders').find(f=>f.name==='工作归档');
  await evaluate(`document.querySelector('#folder-name').value='摄影参考';document.querySelector('#folder-form').requestSubmit()`);await wait('document.querySelector("#folder-list").textContent.includes("摄影参考")');assert.equal(app.store.get('folders',folder.id).name,'摄影参考');
  await evaluate(`document.querySelector('#folder-new').click();document.querySelector('#folder-name').value='摄影参考';document.querySelector('#folder-form').requestSubmit()`);await wait('document.querySelector("#folder-error").textContent.includes("同名")');assert.equal(app.store.list('folders').filter(f=>f.name==='摄影参考').length,1);await evaluate(`document.querySelector('#folder-name').value='待删除归档';document.querySelector('#folder-form').requestSubmit()`);await wait('document.querySelector("#folder-list").textContent.includes("待删除归档")');const temporary=app.store.list('folders').find(f=>f.name==='待删除归档');await evaluate(`document.querySelector('#folder-dialog [data-close]').click();document.querySelector('#asset-folder').value='';document.querySelector('#asset-folder').dispatchEvent(new Event('change'));document.querySelector('#asset-clear-selection').click();document.querySelector('[data-select-asset]').click();document.querySelector('#asset-bulk-folder').value='${temporary.id}';document.querySelector('#asset-move-selected').click()`);await wait(`(async()=>{const s=await(await fetch('/api/state')).json();return s.assets.some(a=>a.folderId==='${temporary.id}');})()`);const moved=app.store.list('assets').find(a=>a.folderId===temporary.id);
  await evaluate(`document.querySelector('#folder-manage').click();document.querySelector('[data-folder-id="${temporary.id}"]').click();document.querySelector('#folder-open').click()`);assert.equal(await evaluate('document.querySelector("#asset-folder").value'),temporary.id);await wait('document.querySelector("#assets-list").textContent.includes('+JSON.stringify(moved.title)+')');
  await evaluate(`document.querySelector('#folder-manage').click();document.querySelector('#folder-delete').click()`);await wait('document.querySelector("#confirm-dialog").open');await evaluate(`document.querySelector('#confirm-dialog [value=cancel]').click()`);assert.ok(app.store.get('folders',temporary.id));await wait('!document.querySelector("#folder-delete").hasAttribute("aria-busy")');await evaluate(`document.querySelector('#folder-delete').click()`);await wait('document.querySelector("#confirm-dialog").open');await evaluate(`document.querySelector('#confirm-dialog [data-confirm-accept]').click()`);await wait('!document.querySelector("#folder-list").textContent.includes("待删除归档")');assert.equal(app.store.get('assets',moved.id).folderId,'');assert.equal(app.store.get('assets',moved.id).content,moved.content);
  await evaluate(`document.querySelector('#folder-search').value='不匹配的词';document.querySelector('#folder-search').dispatchEvent(new Event('input'))`);assert.ok(await evaluate('document.querySelector("#folder-list").textContent.includes("没有匹配")'));await evaluate(`document.querySelector('#folder-search').value='';document.querySelector('#folder-search').dispatchEvent(new Event('input'));document.querySelector('#toast').classList.add('hidden')`);writeFileSync(evidence+'/folders-desktop.png',Buffer.from((await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:true})).data,'base64'));
  await cdp('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await sleep(350);assert.equal(await evaluate('document.documentElement.scrollWidth<=window.innerWidth'),true,'folder manager mobile overflow');writeFileSync(evidence+'/folders-mobile.png',Buffer.from((await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:false})).data,'base64'));await evaluate(`document.querySelector('#folder-dialog [data-close]').click()`);await cdp('Emulation.setDeviceMetricsOverride',{width:1440,height:1100,deviceScaleFactor:1,mobile:false});await sleep(350);await evaluate(`window.scrollTo(0,0);document.querySelector('[data-view=workspace]').click();document.querySelector('#toast').classList.add('hidden')`);await sleep(250);assert.equal(await evaluate('getComputedStyle(document.querySelector(".sidebar")).position'), 'fixed');writeFileSync(evidence+'/fresh-workspace.png',Buffer.from((await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:false})).data,'base64'));


  // 0.3.6: real browser actions with isolated mock inference only.
  await evaluate("document.querySelector('[data-view=workspace]').click()");
  const mockImage=readFileSync('public/icon-256.png').toString('base64');await evaluate("(()=>{const bytes=Uint8Array.from(atob("+JSON.stringify(mockImage)+"),c=>c.charCodeAt(0)),dt=new DataTransfer();dt.items.add(new File([bytes],'mock-reference.png',{type:'image/png'}));document.querySelector('#image-input').files=dt.files;document.querySelector('#image-input').dispatchEvent(new Event('change'));})()");await wait('document.querySelectorAll("#image-previews img").length===1');
  await evaluate("document.querySelector('[data-view=snippets]').click()");
  await wait('document.querySelector("#snippets-list").textContent.includes("没有匹配")');
  await evaluate("document.querySelector('#snippet-add').click();const f=document.querySelector('#snippet-form');f.elements.name.value='验收格式';f.elements.category.value='格式';f.elements.content.value='明确格式，保留 {{literal}}';f.requestSubmit()");
  await wait('!document.querySelector("#snippet-dialog").open && document.querySelector("#snippets-list").textContent.includes("验收格式")');
  const snippet=app.store.list('snippets')[0];
  await evaluate("document.querySelector('#snippets-list [data-lab-action=snippet-edit]').click();document.querySelector('#snippet-form').elements.content.value='明确格式，保留 {{literal}} 与自然光';document.querySelector('#snippet-form').requestSubmit()");
  await wait('!document.querySelector("#snippet-dialog").open');
  await evaluate("document.querySelector('#snippets-list [data-snippet-select]').click();document.querySelector('#snippet-compose').click()");
  await wait('document.querySelector("#compose-dialog").open');
  assert.ok(await evaluate('document.querySelector("#compose-preview").textContent.includes("{{literal}}")'));
  await evaluate("document.querySelector('#compose-apply').click()");
  await wait('!document.querySelector("#compose-dialog").open && document.querySelector("#composition-note").textContent.includes("1 个片段")');
  await evaluate("document.querySelector('#quality-open').click();document.querySelector('#quality-include').value='自然光';document.querySelector('#quality-exclude').value='模糊';document.querySelector('#quality-min').value='4';document.querySelector('#quality-include').dispatchEvent(new Event('change'));document.querySelector('#quality-check').click()");
  await wait('document.querySelector("#quality-result").textContent.includes("规则通过")');
  await evaluate("document.querySelector('#quality-dialog [data-close]').click()");
  assert.equal(await evaluate('document.querySelectorAll("#image-previews img").length'),1,'composition preserves reference images');
  let labCalls=0;app.jobs.generator=async(p,b)=>{labCalls++;await sleep(150);return {output:labCalls===1?'自然光和明确格式，保留所有约束。':'自然光和明确格式，进一步减少重复。',usage:{completion_tokens:20}};};
  await evaluate("document.querySelector('#run').click()");
  await wait('document.querySelector("#output").value.includes("保留所有约束") && !document.querySelector("#run").disabled');
  const parent=app.store.list('jobs').find(j=>j.output==='自然光和明确格式，保留所有约束。');assert.equal(parent.snippets[0].id,snippet.id);assert.equal(parent.input.split('【验收格式】').length,2);assert.equal(parent.quality.pass,true);
  await wait('!document.querySelector("#iterate-output").disabled');
  await evaluate("document.querySelector('#iterate-output').click()");await wait('document.querySelector("#iteration-dialog").open');
  await evaluate("document.querySelector('#iteration-instruction').value='减少重复，保留自然光';document.querySelector('#iteration-form').requestSubmit()");
  await wait('!document.querySelector("#iteration-dialog").open && document.querySelector("#output").value.includes("进一步减少重复") && !document.querySelector("#run").disabled');
  assert.equal(labCalls,2);const childJob=app.store.list('jobs').find(j=>j.parentJobId===parent.id);assert.ok(childJob);assert.equal(childJob.parentSnapshot.output,parent.output);assert.equal(childJob.quality.pass,true);
  await evaluate("document.querySelector('[data-view=compare]').click()");await wait('document.querySelectorAll("#compare-left option").length>1');
  await evaluate("document.querySelector('#compare-left').value="+JSON.stringify(parent.id)+";document.querySelector('#compare-right').value="+JSON.stringify(childJob.id)+";document.querySelector('#compare-run').click()");
  await wait('document.querySelectorAll("#compare-results .comparison").length===2');assert.ok(await evaluate('document.querySelector("#compare-note").textContent.includes("生成条件不同")'));assert.ok(await evaluate('document.querySelector("#compare-note").textContent.includes("同一迭代链")'));assert.equal(labCalls,2);
  await evaluate("document.querySelector('#toast').classList.add('hidden');window.scrollTo(0,0)");writeFileSync(evidence+'/comparison-desktop.png',Buffer.from((await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:false})).data,'base64'));
  assert.equal(await evaluate('document.documentElement.scrollWidth<=window.innerWidth'),true,'comparison desktop overflow');
  // Selection survives changing search, so users can find each side separately.
  await evaluate("document.querySelector('#compare-search').value='不匹配';document.querySelector('#compare-search').dispatchEvent(new Event('input'))");await wait('document.querySelector("#compare-count").textContent.includes("0 条")');assert.equal(await evaluate('document.querySelector("#compare-left").value'),parent.id);
  await evaluate("document.querySelector('[data-view=snippets]').click()");await wait('document.querySelector("#snippets-list").textContent.includes("验收格式")');
  await evaluate("document.querySelector('#snippets-list [data-lab-action=snippet-delete]').click()");await wait('document.querySelector("#confirm-dialog").open');await evaluate("document.querySelector('#confirm-dialog [data-confirm-accept]').click()");await wait('!document.querySelector("#snippets-list").textContent.includes("验收格式")');
  assert.ok(app.store.get('snippets',snippet.id).deletedAt);assert.equal(app.store.get('jobs',parent.id).snippets[0].content,parent.snippets[0].content);
  await evaluate("document.querySelector('[data-view=recycle]').click();document.querySelector('#trash-kind').value='snippets';document.querySelector('#trash-kind').dispatchEvent(new Event('change'))");await wait('document.querySelector("#trash-list").textContent.includes("验收格式")');await evaluate("document.querySelector('#trash-list .secondary').click()");await wait('!document.querySelector("#trash-list").textContent.includes("验收格式")');assert.equal(app.store.get('snippets',snippet.id).deletedAt,null);
  await evaluate("document.querySelector('[data-view=snippets]').click()");await wait('document.querySelector("#snippets-list").textContent.includes("验收格式")');writeFileSync(evidence+'/snippets-desktop.png',Buffer.from((await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:false})).data,'base64'));
  await cdp('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await sleep(350);
  for(const view of ['workspace','compare','snippets']){await evaluate("document.querySelector('[data-view="+view+"]').click();window.scrollTo(0,0)");await sleep(200);assert.equal(await evaluate('document.documentElement.scrollWidth<=window.innerWidth'),true,'lab mobile overflow '+view);if(view==='compare')writeFileSync(evidence+'/comparison-mobile.png',Buffer.from((await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:false})).data,'base64'));}
  await cdp('Emulation.setDeviceMetricsOverride',{width:1440,height:1100,deviceScaleFactor:1,mobile:false});await sleep(350);
  await evaluate("document.querySelector('[data-view=workspace]').click();document.querySelector('#quality-open').click()");await wait('document.querySelector("#quality-dialog").open');assert.equal(await evaluate('document.querySelector("#quality-include").value'),'自然光');await evaluate("document.querySelector('#quality-check').click()");await wait('document.querySelector("#quality-result").textContent.includes("3 / 3")');writeFileSync(evidence+'/quality-desktop.png',Buffer.from((await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:false})).data,'base64'));await evaluate("document.querySelector('#quality-dialog [data-close]').click()");

  await evaluate("document.querySelector('#quality-include').value='其他任务规则';document.querySelector('[data-view=history]').click()");const parentSelector='#jobs-list [data-action="job-use"][data-id="'+parent.id+'"]';await wait('document.querySelector('+JSON.stringify(parentSelector)+')');await evaluate('document.querySelector('+JSON.stringify(parentSelector)+').click()');await wait('document.querySelector("#quality-include").value==="自然光"');
  await wait('document.querySelector("#quality-exclude").value==="模糊"');await sleep(650);
  await cdp('Page.reload');await wait('document.querySelectorAll("#template-select option").length>=7');await wait('document.querySelector("#quality-include").value==="自然光"');assert.equal(labCalls,2,'reload/check/compare never trigger inference');


  // 0.3.7: TXT confirmation and native browser-produced playable WebM.
  await evaluate("document.querySelector('[data-view=library]').click();document.querySelector('#asset-scope').value='all';document.querySelector('#asset-folder').value='';document.querySelector('#asset-search').value='';document.querySelector('#asset-tag-filter').value='';document.querySelector('#asset-folder').dispatchEvent(new Event('change'))");
  const importBefore=app.store.list('assets').length;
  await evaluate("(()=>{const dt=new DataTransfer();dt.items.add(new File(['纯文本：自然光与木材'],'纯文本.txt',{type:'text/plain'}));document.querySelector('header').dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:dt}));})()");await wait('document.querySelector("#asset-dialog").open');assert.equal(await evaluate('document.querySelector("#asset-form").elements.negative.value'),'');assert.ok(await evaluate('document.querySelector("#asset-import-info").open && document.querySelector("#asset-import-note").textContent.includes("纯文本")'));await evaluate("document.querySelector('#asset-dialog [data-close]').click()");assert.equal(app.store.list('assets').length,importBefore);
  const assetTxt=['标题：拖拽图文案例','主题：空间, 自然光','正向提示词：温暖阅读角，保留自然采光和木材。','负向提示词：模糊、过曝','模型：通用'].join(String.fromCharCode(10));
  await evaluate("(()=>{const dt=new DataTransfer();dt.items.add(new File(["+JSON.stringify(assetTxt)+"],'空间案例.txt',{type:'text/plain'}));const bytes=Uint8Array.from(atob("+JSON.stringify(mockImage)+"),c=>c.charCodeAt(0));dt.items.add(new File([bytes],'效果图.png',{type:'image/png'}));document.querySelector('#library').dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:dt}));})()");await wait('document.querySelector("#asset-dialog").open && document.querySelectorAll("#asset-media-previews img").length===1');
  assert.equal(await evaluate('document.querySelector("#asset-form").elements.title.value'),'拖拽图文案例');assert.equal(await evaluate('document.querySelector("#asset-form").elements.negative.value'),'模糊、过曝');assert.equal(await evaluate('document.querySelector("#asset-form").elements.tags.value'),'空间, 自然光');assert.equal(app.store.list('assets').length,importBefore);
  const webm=await evaluate("(async()=>{const canvas=document.createElement('canvas');canvas.width=160;canvas.height=120;const ctx=canvas.getContext('2d'),stream=canvas.captureStream(10),chunks=[];const mime=MediaRecorder.isTypeSupported('video/webm;codecs=vp8')?'video/webm;codecs=vp8':'video/webm';const recorder=new MediaRecorder(stream,{mimeType:mime});return await new Promise((resolve,reject)=>{recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onerror=e=>reject(Error(e.error?.message||'录制失败'));recorder.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());const bytes=new Uint8Array(await new Blob(chunks,{type:mime}).arrayBuffer());resolve(btoa(Array.from(bytes,b=>String.fromCharCode(b)).join('')));};recorder.start(100);let frame=0;const tick=setInterval(()=>{ctx.fillStyle=frame++%2?'#a9cee9':'#f1debc';ctx.fillRect(0,0,160,120);ctx.fillStyle='#326fa7';ctx.fillRect(30,30,70,40);},70);setTimeout(()=>{clearInterval(tick);recorder.stop();},700);});})()");
  await evaluate("(()=>{const bytes=Uint8Array.from(atob("+JSON.stringify(webm)+"),c=>c.charCodeAt(0)),dt=new DataTransfer();dt.items.add(new File([bytes],'预览视频.webm',{type:'video/webm'}));document.querySelector('#asset-media-drop').dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:dt}));})()");await wait('document.querySelectorAll("#asset-media-previews video").length===1');assert.equal(await evaluate('document.querySelectorAll("#asset-media-previews img").length'),1,'cancel/reopen preserves the new image');await wait('document.querySelector("#asset-media-previews video").readyState>=1');assert.equal(app.store.list('assets').length,importBefore);
  await evaluate("document.querySelector('#toast').classList.add('hidden');document.querySelector('#asset-dialog').scrollTop=0");writeFileSync(evidence+'/txt-confirm-desktop.png',Buffer.from((await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:false})).data,'base64'));
  await evaluate("document.querySelector('#asset-form').requestSubmit()");await wait('!document.querySelector("#asset-dialog").open');await wait('document.querySelector("#assets-list").textContent.includes("拖拽图文案例")');const importedAsset=app.store.list('assets').find(a=>a.title==='拖拽图文案例');assert.equal(importedAsset.media.length,2);assert.equal(importedAsset.negative,'模糊、过曝');assert.ok(importedAsset.importInfo.raw.includes('主题'));assert.equal(app.store.list('assets').length,importBefore+1);
  const importCardTitleSelector='[data-asset-card="'+importedAsset.id+'"] h3';await evaluate('document.querySelector('+JSON.stringify(importCardTitleSelector)+').click()');await wait('document.querySelector("#asset-detail-dialog").open');await wait('document.querySelector("#asset-detail video").readyState>=1');assert.equal(await evaluate('document.querySelector("#asset-detail img").naturalWidth>0'),true);await evaluate("document.querySelector('#asset-detail video').muted=true;document.querySelector('#asset-detail video').play()");await wait('!document.querySelector("#asset-detail video").paused');writeFileSync(evidence+'/personal-media-detail.png',Buffer.from((await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:false})).data,'base64'));await evaluate("document.querySelector('#asset-detail-dialog [data-close]').click()");assert.equal(await evaluate('document.querySelector("#asset-detail video").paused'),true,'closing stops video playback');
  await evaluate('document.querySelector('+JSON.stringify('[data-action="asset-edit"][data-id="'+importedAsset.id+'"]')+').click()');await wait('document.querySelector("#asset-dialog").open');assert.equal(await evaluate('document.querySelectorAll("#asset-media-previews figure").length'),2);await evaluate("document.querySelector('#asset-form').elements.note.value='修改备注，素材保留';document.querySelector('#asset-form').requestSubmit()");await wait('!document.querySelector("#asset-dialog").open');assert.equal(app.store.get('assets',importedAsset.id).media.length,2);

  await evaluate("(()=>{document.querySelector('#asset-import').click();const dt=new DataTransfer();dt.items.add(new File(['正向提示词：通过按钮导入的新提示词'],'按钮导入.txt',{type:'text/plain'}));document.querySelector('#import-file').files=dt.files;document.querySelector('#import-file').dispatchEvent(new Event('change'));})()");await wait('document.querySelector("#asset-dialog").open && document.querySelector("#asset-form").elements.content.value.includes("通过按钮导入")');assert.equal(await evaluate('document.querySelector("#asset-form").elements.id.value'),'','new TXT after editing never reuses hidden id');assert.equal(await evaluate('document.querySelectorAll("#asset-media-previews figure").length'),0);await evaluate("document.querySelector('#asset-dialog [data-close]').click()");assert.equal(app.store.list('assets').length,importBefore+1);

  await evaluate("document.querySelector('#toast').classList.add('hidden');window.scrollTo(0,0)");writeFileSync(evidence+'/personal-gallery-desktop.png',Buffer.from((await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:false})).data,'base64'));
  await cdp('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await sleep(350);assert.equal(await evaluate('document.documentElement.scrollWidth<=window.innerWidth'),true,'personal media gallery mobile overflow');writeFileSync(evidence+'/personal-gallery-mobile.png',Buffer.from((await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:false})).data,'base64'));await evaluate('document.querySelector('+JSON.stringify('[data-action="asset-edit"][data-id="'+importedAsset.id+'"]')+').click()');await wait('document.querySelector("#asset-dialog").open');assert.equal(await evaluate('document.documentElement.scrollWidth<=window.innerWidth'),true,'attachment editor mobile overflow');writeFileSync(evidence+'/txt-confirm-mobile.png',Buffer.from((await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:false})).data,'base64'));await evaluate("document.querySelector('#asset-dialog [data-close]').click()");
  await cdp('Emulation.setDeviceMetricsOverride',{width:1440,height:1100,deviceScaleFactor:1,mobile:false});await sleep(350);assert.equal(labCalls,2,'media/TXT import never generates');


  const formatFence=String.fromCharCode(96).repeat(3);
  for(const sample of [{name:'示例.md',text:['# 空间示例','#### ✅ 正面提示词 (Positive Prompt)',formatFence+'text','木材与自然光',formatFence,'#### ❌ 负面提示词 (Negative Prompt)',formatFence+'text','模糊',formatFence,'### 说明','保留到备注'].join(String.fromCharCode(10))},{name:'示例.json',text:JSON.stringify({title:'JSON示例',positive_prompt:'木材与自然光',negative_prompt:'模糊',tags:['空间']})},{name:'示例.jons',text:JSON.stringify({positive:'木材与自然光',negative:'模糊'})},{name:'示例.yaml',text:['positive: 木材与自然光','negative: 模糊'].join(String.fromCharCode(10))}]){
    await evaluate("(()=>{const dt=new DataTransfer();dt.items.add(new File(["+JSON.stringify(sample.text)+"],"+JSON.stringify(sample.name)+",{type:'text/plain'}));document.querySelector('#library').dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:dt}));})()");await wait('document.querySelector("#asset-dialog").open && document.querySelector("#asset-form").elements.content.value==="木材与自然光"');assert.equal(await evaluate('document.querySelector("#asset-form").elements.negative.value'),'模糊');await evaluate("document.querySelector('#asset-dialog [data-close]').click()");await sleep(50);
  }
  await evaluate("(()=>{document.querySelector('#asset-import').click();const dt=new DataTransfer();dt.items.add(new File([JSON.stringify({title:'按钮JSON',positive:'按钮正文',negative:'按钮负向'})],'button.json',{type:'application/json'}));document.querySelector('#import-file').files=dt.files;document.querySelector('#import-file').dispatchEvent(new Event('change'));})()");await wait('document.querySelector("#asset-dialog").open && document.querySelector("#asset-form").elements.content.value==="按钮正文"');assert.equal(app.store.list('assets').length,importBefore+1,'ordinary JSON requires confirmation');await evaluate("document.querySelector('#asset-dialog [data-close]').click()");assert.equal(labCalls,2);

await evaluate("document.querySelector('[data-view=inbox]').click()");await wait('document.querySelector("[data-review-inbox]")');await evaluate("document.querySelector('[data-review-inbox]').click()");await wait('document.querySelector("#inbox-dialog").open');
assert.equal(await evaluate("(()=>{const a=document.querySelector('#inbox-images').getBoundingClientRect(),b=document.querySelector('#inbox-content').getBoundingClientRect();return a.right<=b.left;})()"),true);writeFileSync(evidence+'/inbox-dialog-desktop.png',Buffer.from((await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:false})).data,'base64'));await evaluate("document.querySelector('#inbox-dialog [data-close]').click()");
await cdp('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await sleep(350);await evaluate("document.querySelector('[data-review-inbox]').click()");await wait('document.querySelector("#inbox-dialog").open');assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true);writeFileSync(evidence+'/inbox-dialog-mobile.png',Buffer.from((await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:false})).data,'base64'));await evaluate("document.querySelector('#inbox-dialog [data-close]').click()");
  assert.deepEqual(errors,[]);writeFileSync(evidence+'/ui-result.json',JSON.stringify({status:'PASS',mode:'Chrome headless; mocked inference and shared data',checks:['generation','model dropdown applied to job','asset save','folder create','favorite','asset trash/restore','history multiselect/trash/restore','template create','shared detail/collect','desktop no overflow','mobile no overflow','template trash/restore/purge','database diagnostic','incremental text before completion','busy output protection','dark theme','old selected task outside 250-row state','keyboard batch duplicate guard','folder manager create/rename/search/view','folder duplicate error','folder cancel/delete preserves assets','confirmation without typing','snippet create/edit/compose literal snapshot and reference preservation','snippet trash/restore preserves jobs','iteration submits once and retains parent','comparison conditions and selection across searches','local rules persist after reload','lab desktop/mobile layouts','TXT drag parse and confirm/cancel','image and playable native WebM drop/preview/save','media gallery/detail/edit preservation','close pauses video','media desktop/mobile layout','Markdown/JSON/JONS/YAML drag preview','ordinary JSON picker requires confirmation','no runtime exceptions'],realModel:false},null,2));
  // 对现有 SVG 进行文件格式转换，桌面图标与网页采用同一份设计。
  if(process.env.PW_GENERATE_ICONS==='1'){const sizes=[16,32,48,64,128,256],pngs=[];await cdp('Emulation.setDefaultBackgroundColorOverride',{color:{r:0,g:0,b:0,a:0}});await cdp('Page.navigate',{url:`http://127.0.0.1:${app.port}/icon.svg`});
  for(const size of sizes){await cdp('Emulation.setDeviceMetricsOverride',{width:size,height:size,deviceScaleFactor:1,mobile:false});await sleep(100);const png=Buffer.from((await cdp('Page.captureScreenshot',{format:'png'})).data,'base64');pngs.push(png);if(size===256)writeFileSync('public/icon-256.png',png);}
  const header=Buffer.alloc(6+16*sizes.length);header.writeUInt16LE(1,2);header.writeUInt16LE(sizes.length,4);let offset=header.length;
  sizes.forEach((size,i)=>{const p=6+16*i;header[p]=size===256?0:size;header[p+1]=size===256?0:size;header.writeUInt16LE(1,p+4);header.writeUInt16LE(32,p+6);header.writeUInt32LE(pngs[i].length,p+8);header.writeUInt32LE(offset,p+12);offset+=pngs[i].length;});writeFileSync('public/workbench.ico',Buffer.concat([header,...pngs]));}
  console.log('浏览器界面验收通过：生成、收藏、模板、历史、桌面与手机布局。');await cdp('Browser.close').catch(()=>{});
}catch(e){writeFileSync(evidence+'/ui-result.json',JSON.stringify({status:'FAIL',error:e.message,realModel:false},null,2));throw e;}finally{if(ws)ws.close();if(child.exitCode===null)child.kill();await app.close();}
