// 用户确认S05–S37试用；原目录与许可核查见docs/research/prompt-sources-2026-10-08。
export const EXTRA_FEEDS = [
  {
    "id": "s05",
    "auditId": "S05",
    "name": "LangGPT · GPT-4o prompts",
    "url": "https://github.com/langgptai/awesome-gpt-4o-prompts",
    "license": "Apache-2.0 · 原帖作者另见出处",
    "description": "建筑模型、摆件、绳结等案例，正文附X来源",
    "group": "图文仓库",
    "adapter": "markdown",
    "repo": "langgptai/awesome-gpt-4o-prompts",
    "path": "README.md",
    "syncable": true,
    "contentKind": "images",
    "notice": "个人试用来源；保留作者/原帖/许可，未承诺生成复现。"
  },
  {
    "id": "s06",
    "auditId": "S06",
    "name": "ZeroLu · Awesome GPT Image",
    "url": "https://github.com/ZeroLu/awesome-gpt-image",
    "license": "MIT · 原帖和媒体权利另核",
    "description": "摄影、海报、UI、编辑等图文案例，含中文README",
    "group": "图文仓库",
    "adapter": "markdown",
    "repo": "ZeroLu/awesome-gpt-image",
    "path": "README.zh-CN.md",
    "syncable": true,
    "contentKind": "images",
    "notice": "个人试用来源；保留作者/原帖/许可，未承诺生成复现。"
  },
  {
    "id": "s07",
    "auditId": "S07",
    "name": "NanoBanana Trending Prompts · jau123",
    "url": "https://github.com/jau123/nanobanana-trending-prompts",
    "license": "CC BY 4.0 · MeiGen；保留原帖作者",
    "description": "仓库描述为X热门图像提示词集合；有prompts目录",
    "group": "图文仓库",
    "adapter": "meigen",
    "repo": "jau123/nanobanana-trending-prompts",
    "path": "prompts/prompts.json",
    "syncable": true,
    "contentKind": "images",
    "notice": "个人试用来源；保留作者/原帖/许可，未承诺生成复现。"
  },
  {
    "id": "s08",
    "auditId": "S08",
    "name": "Awesome Nano Banana · JimmyLv",
    "url": "https://github.com/JimmyLv/awesome-nano-banana",
    "license": "CC BY 4.0 · 部分素材许可例外",
    "description": "图像编辑案例集合；目录含cases和case-template",
    "group": "图文仓库",
    "adapter": "markdown",
    "repo": "JimmyLv/awesome-nano-banana",
    "path": "README.md",
    "syncable": true,
    "contentKind": "images",
    "notice": "个人试用来源；保留作者/原帖/许可，未承诺生成复现。"
  },
  {
    "id": "s09",
    "auditId": "S09",
    "name": "NeXra · AI Image Prompts",
    "url": "https://github.com/NeXra-AI/awesome-ai-image-prompts",
    "license": "逐条许可 · 聚合标注不代表原作者授权",
    "description": "README列出结构化JSON、作者、source_url和逐条license",
    "group": "图文仓库",
    "adapter": "nexra",
    "repo": "NeXra-AI/awesome-ai-image-prompts",
    "path": "data/prompts.json",
    "syncable": true,
    "contentKind": "images",
    "notice": "个人试用来源；保留作者/原帖/许可，未承诺生成复现。"
  },
  {
    "id": "s10",
    "auditId": "S10",
    "name": "Nano Banana Prompts · flaqai",
    "url": "https://github.com/flaqai/awesome-nano-banana-prompts",
    "license": "MIT · Flaq AI 原创模板",
    "description": "图像提示词配方与视觉参考，支持多语言",
    "group": "图文仓库",
    "adapter": "recipes",
    "repo": "flaqai/awesome-nano-banana-prompts",
    "path": "README.md",
    "syncable": true,
    "contentKind": "text",
    "notice": "个人试用来源；保留作者/原帖/许可，未承诺生成复现。"
  },
  {
    "id": "s11",
    "auditId": "S11",
    "name": "GPT Image / Nano Banana 对比图库 · AI尹小歪",
    "url": "https://github.com/yinxiaowai/awesome-gpt-image-2-vs-nano-banana-2-prompt-gallery",
    "license": "CC BY-NC 4.0 · 仅供个人非商业试用",
    "description": "中文案例与并排模型输出；读取到UI案例正文",
    "group": "图文仓库",
    "adapter": "markdown",
    "repo": "yinxiaowai/awesome-gpt-image-2-vs-nano-banana-2-prompt-gallery",
    "path": "README.md",
    "syncable": true,
    "contentKind": "images",
    "notice": "个人试用来源；保留作者/原帖/许可，未承诺生成复现。"
  },
  {
    "id": "s12",
    "auditId": "S12",
    "name": "YouMind 提示词库",
    "url": "https://youmind.com/zh-CN/prompts",
    "license": "未确认开放再使用许可 · 保留原作者",
    "description": "页面含图像、视频、建站分类和作者、详情入口",
    "group": "图像与综合社区",
    "adapter": "manual",
    "repo": "",
    "path": "",
    "syncable": false,
    "contentKind": "text",
    "notice": "原站限制自动采集；请访问原站，或导入你有权使用的提示词文件。"
  },
  {
    "id": "s13",
    "auditId": "S13",
    "name": "PromptHero",
    "url": "https://prompthero.com/",
    "license": "未确认开放再使用许可 · 保留原作者",
    "description": "页面可读图文提示词，覆盖多模型；有MiniMax H3标识案例",
    "group": "图像与综合社区",
    "adapter": "manual",
    "repo": "",
    "path": "",
    "syncable": false,
    "contentKind": "text",
    "notice": "尚无已核实的稳定公开数据接口；可访问原帖后导入文件。"
  },
  {
    "id": "s14",
    "auditId": "S14",
    "name": "ImagePrompts",
    "url": "https://imageprompts.co/zh",
    "license": "未确认开放再使用许可 · 保留原作者",
    "description": "中文图像提示词目录，按模型和场景浏览",
    "group": "图像与综合社区",
    "adapter": "manual",
    "repo": "",
    "path": "",
    "syncable": false,
    "contentKind": "text",
    "notice": "详情结构和内容授权尚未确认；可人工选取后导入。"
  },
  {
    "id": "s15",
    "auditId": "S15",
    "name": "AI妙词",
    "url": "https://aimiaoci.com/",
    "license": "未确认开放再使用许可 · 保留原作者",
    "description": "中文图像与网页提示词分类库",
    "group": "图像与综合社区",
    "adapter": "manual",
    "repo": "",
    "path": "",
    "syncable": false,
    "contentKind": "text",
    "notice": "正文结构和授权尚未确认；可人工选取后导入。"
  },
  {
    "id": "s16",
    "auditId": "S16",
    "name": "AI百宝箱 · 提示词库",
    "url": "https://www.wangzhidaquan.com/prompts/",
    "license": "未确认开放再使用许可 · 保留原作者",
    "description": "写作、编程、办公、绘画等分类，页面含可复制正文",
    "group": "图像与综合社区",
    "adapter": "html-prompts",
    "repo": "",
    "path": "",
    "syncable": true,
    "contentKind": "text",
    "notice": "个人试用来源；保留作者/原帖/许可，未承诺生成复现。"
  },
  {
    "id": "s17",
    "auditId": "S17",
    "name": "Lexica",
    "url": "https://lexica.art/",
    "license": "未确认开放再使用许可 · 保留原作者",
    "description": "图像搜索站点入口",
    "group": "图像与综合社区",
    "adapter": "manual",
    "repo": "",
    "path": "",
    "syncable": false,
    "contentKind": "text",
    "notice": "搜索站暂无可用公开正文接口；可人工选取后导入。"
  },
  {
    "id": "s18",
    "auditId": "S18",
    "name": "OpenArt Discovery",
    "url": "https://openart.ai/discovery",
    "license": "未确认开放再使用许可 · 保留原作者",
    "description": "图像发现入口",
    "group": "图像与综合社区",
    "adapter": "manual",
    "repo": "",
    "path": "",
    "syncable": false,
    "contentKind": "text",
    "notice": "当前入口未能取得完整正文；可人工选取后导入。"
  },
  {
    "id": "s19",
    "auditId": "S19",
    "name": "Civitai Images",
    "url": "https://civitai.com/images",
    "license": "未确认开放再使用许可 · 保留原作者",
    "description": "图像社区审核入口",
    "group": "图像与综合社区",
    "adapter": "manual",
    "repo": "",
    "path": "",
    "syncable": false,
    "contentKind": "text",
    "notice": "当前公开读取受限；不绕过验证，可导入你取得的提示词文件。"
  },
  {
    "id": "s20",
    "auditId": "S20",
    "name": "SeaArt Explore",
    "url": "https://www.seaart.ai/explore",
    "license": "未确认开放再使用许可 · 保留原作者",
    "description": "图像与视频社区入口",
    "group": "图像与综合社区",
    "adapter": "manual",
    "repo": "",
    "path": "",
    "syncable": false,
    "contentKind": "text",
    "notice": "发现入口未取得完整提示词；可人工选取后导入。"
  },
  {
    "id": "s21",
    "auditId": "S21",
    "name": "Tensor.Art Posts",
    "url": "https://tensor.art/posts",
    "license": "未确认开放再使用许可 · 保留原作者",
    "description": "图像社区分类入口",
    "group": "图像与综合社区",
    "adapter": "manual",
    "repo": "",
    "path": "",
    "syncable": false,
    "contentKind": "text",
    "notice": "工作流与正文接口未核实；可导入含正负词的文件。"
  },
  {
    "id": "s22",
    "auditId": "S22",
    "name": "ChatGPT 中文调教指南 · PlexPt",
    "url": "https://github.com/PlexPt/awesome-chatgpt-prompts-zh",
    "license": "MIT · PlexPt",
    "description": "中文提示词仓库，有prompts-zh.json文件",
    "group": "文字与模板",
    "adapter": "act-json",
    "repo": "PlexPt/awesome-chatgpt-prompts-zh",
    "path": "prompts-zh.json",
    "syncable": true,
    "contentKind": "text",
    "notice": "个人试用来源；保留作者/原帖/许可，未承诺生成复现。"
  },
  {
    "id": "s23",
    "auditId": "S23",
    "name": "ChatGPT 提示词中文合集 · CHENJIAMIAN",
    "url": "https://github.com/CHENJIAMIAN/awesome-chatgpt-prompts-zh-CN",
    "license": "CC0 · prompts.chat 中文译本；不含AIPRM",
    "description": "中文CSV、JSON、分卷Markdown；另附AIPRM快照",
    "group": "文字与模板",
    "adapter": "translated-json",
    "repo": "CHENJIAMIAN/awesome-chatgpt-prompts-zh-CN",
    "path": "chatgpt_prompts-zh-CN.json",
    "syncable": true,
    "contentKind": "text",
    "notice": "个人试用来源；保留作者/原帖/许可，未承诺生成复现。"
  },
  {
    "id": "s24",
    "auditId": "S24",
    "name": "Wonderful Prompts · LangGPT",
    "url": "https://github.com/langgptai/wonderful-prompts",
    "license": "MIT · LangGPT / yzfly",
    "description": "中文精选提示词与examples目录",
    "group": "文字与模板",
    "adapter": "markdown",
    "repo": "langgptai/wonderful-prompts",
    "path": "README.md",
    "syncable": true,
    "contentKind": "text",
    "notice": "个人试用来源；保留作者/原帖/许可，未承诺生成复现。"
  },
  {
    "id": "s25",
    "auditId": "S25",
    "name": "LangGPT",
    "url": "https://github.com/langgptai/LangGPT",
    "license": "Apache-2.0 · LangGPT",
    "description": "结构化角色和元提示词框架与示例",
    "group": "文字与模板",
    "adapter": "markdown",
    "repo": "langgptai/LangGPT",
    "path": "README.md",
    "syncable": true,
    "contentKind": "text",
    "notice": "个人试用来源；保留作者/原帖/许可，未承诺生成复现。"
  },
  {
    "id": "s26",
    "auditId": "S26",
    "name": "Awesome Prompts · ai-boost",
    "url": "https://github.com/ai-boost/awesome-prompts",
    "license": "GPL-3.0 · 第三方条目权利另核",
    "description": "多领域系统提示词目录，包含legacy分类",
    "group": "文字与模板",
    "adapter": "markdown",
    "repo": "ai-boost/awesome-prompts",
    "path": "README.md",
    "syncable": true,
    "contentKind": "text",
    "notice": "个人试用来源；保留作者/原帖/许可，未承诺生成复现。"
  },
  {
    "id": "s27",
    "auditId": "S27",
    "name": "AIPRM",
    "url": "https://www.aiprm.com/prompts/",
    "license": "未确认开放再使用许可 · 保留原作者",
    "description": "公开提示词模板目录",
    "group": "文字与模板",
    "adapter": "manual",
    "repo": "",
    "path": "",
    "syncable": false,
    "contentKind": "text",
    "notice": "原站要求安装/登录且没有核实的全文数据源；本项目不接账号。"
  },
  {
    "id": "s28",
    "auditId": "S28",
    "name": "FlowGPT",
    "url": "https://flowgpt.com/",
    "license": "未确认开放再使用许可 · 保留原作者",
    "description": "角色与AI应用社区；官方指南有Character/Scenario/System Message说明",
    "group": "文字与模板",
    "adapter": "manual",
    "repo": "",
    "path": "",
    "syncable": false,
    "contentKind": "text",
    "notice": "角色应用未提供已核实的完整词库；可导入公开提示词文件。"
  },
  {
    "id": "s29",
    "auditId": "S29",
    "name": "PromptBase",
    "url": "https://promptbase.com/",
    "license": "未确认开放再使用许可 · 保留原作者",
    "description": "图像、文字和视频提示词市场，含免费与付费入口",
    "group": "文字与模板",
    "adapter": "manual",
    "repo": "",
    "path": "",
    "syncable": false,
    "contentKind": "text",
    "notice": "商品正文需购买或授权；本项目不自动购买，可导入你有权使用的文件。"
  },
  {
    "id": "s30",
    "auditId": "S30",
    "name": "Kling Prompts · KingVid",
    "url": "https://github.com/kingvid-ai/awesome-kling-4-prompts",
    "license": "未确认开放再使用许可 · 保留原作者",
    "description": "视频案例、部分正文和Original source链接",
    "group": "视频案例",
    "adapter": "markdown",
    "repo": "kingvid-ai/awesome-kling-4-prompts",
    "path": "README.md",
    "syncable": true,
    "contentKind": "text",
    "notice": "个人试用来源；保留作者/原帖/许可，未承诺生成复现。"
  },
  {
    "id": "s31",
    "auditId": "S31",
    "name": "Kling 3.0 Prompts · ImagineVid",
    "url": "https://github.com/imagineVid/Awesome-kling-3-0-prompts-and-skills",
    "license": "CC BY 4.0 · 第三方素材除外",
    "description": "视频提示词、参考素材和运镜方向",
    "group": "视频案例",
    "adapter": "markdown",
    "repo": "imagineVid/Awesome-kling-3-0-prompts-and-skills",
    "path": "README.md",
    "syncable": true,
    "contentKind": "text",
    "notice": "个人试用来源；保留作者/原帖/许可，未承诺生成复现。"
  },
  {
    "id": "s32",
    "auditId": "S32",
    "name": "Kling Prompts · Reviral",
    "url": "https://github.com/Reviral-ai/awesome-kling-prompts",
    "license": "MIT · Reviral",
    "description": "文生视频、图生视频、运动与产品类配方",
    "group": "视频案例",
    "adapter": "markdown",
    "repo": "Reviral-ai/awesome-kling-prompts",
    "path": "README.md",
    "syncable": true,
    "contentKind": "text",
    "notice": "个人试用来源；保留作者/原帖/许可，未承诺生成复现。"
  },
  {
    "id": "s33",
    "auditId": "S33",
    "name": "VIBE Video Prompt Library",
    "url": "https://www.createvideoai.app/prompts",
    "license": "未确认开放再使用许可 · 保留原作者",
    "description": "视频提示词库，目录包括Hailuo、Kling、WAN等",
    "group": "视频案例",
    "adapter": "video-index",
    "repo": "",
    "path": "",
    "syncable": true,
    "contentKind": "text",
    "notice": "个人试用来源；保留作者/原帖/许可，未承诺生成复现。"
  },
  {
    "id": "s34",
    "auditId": "S34",
    "name": "AIWan Prompt Library",
    "url": "https://aiwan.video/prompts",
    "license": "未确认开放再使用许可 · 保留原作者",
    "description": "视频案例目录，含时长、比例与模型标签",
    "group": "视频案例",
    "adapter": "video-index",
    "repo": "",
    "path": "",
    "syncable": true,
    "contentKind": "text",
    "notice": "个人试用来源；保留作者/原帖/许可，未承诺生成复现。"
  },
  {
    "id": "s35",
    "auditId": "S35",
    "name": "DiffusionDB",
    "url": "https://huggingface.co/datasets/poloclub/diffusiondb",
    "license": "未确认开放再使用许可 · 保留原作者",
    "description": "大规模Stable Diffusion提示词与图像数据集",
    "group": "研究数据集",
    "adapter": "manual",
    "repo": "",
    "path": "",
    "syncable": false,
    "contentKind": "text",
    "notice": "百万级研究库，先导入精选JSON/文本样本，不自动下载整库。"
  },
  {
    "id": "s36",
    "auditId": "S36",
    "name": "VidProM",
    "url": "https://github.com/WangWenhao0716/VidProM",
    "license": "未确认开放再使用许可 · 保留原作者",
    "description": "NeurIPS 2024真实视频提示词数据集项目",
    "group": "研究数据集",
    "adapter": "manual",
    "repo": "WangWenhao0716/VidProM",
    "path": "",
    "syncable": false,
    "contentKind": "text",
    "notice": "视频研究库，先导入精选提示词样本，不自动下载媒体。"
  },
  {
    "id": "s37",
    "auditId": "S37",
    "name": "PromptSource",
    "url": "https://github.com/bigscience-workshop/promptsource",
    "license": "未确认开放再使用许可 · 保留原作者",
    "description": "面向数据集任务的自然语言模板工具与仓库",
    "group": "研究数据集",
    "adapter": "manual",
    "repo": "bigscience-workshop/promptsource",
    "path": "",
    "syncable": false,
    "contentKind": "text",
    "notice": "数据集绑定模板，先导入整理成文字的样本，不执行Jinja。"
  }
];
