import{coverUrl}from'./image-cache.js';
import{saveAsset}from'./library.js';
export function xId(raw){try{const u=new URL(raw);if(u.protocol!=='https:'||!['x.com','twitter.com','www.x.com','www.twitter.com'].includes(u.hostname)||u.username||u.password||u.port)throw Error();const m=u.pathname.match(/^\/[\w]+\/status\/(\d{10,25})(?:\/(?:photo|video)\/\d+)?\/?$/);if(!m)throw Error();return m[1];}catch{throw Error('请提供有效的公开X帖子链接');}}
export class XInbox{
  constructor(store,{fetcher=fetch}={}){this.store=store;this.fetcher=fetcher;this.busy=new Set();}
  manage({ids,action}){if(!Array.isArray(ids)||ids.length>1000||ids.some(id=>typeof id!=='string'||!/^\d{10,25}$/.test(id))||!['trash','restore'].includes(action))throw Error('清理参数无效');this.store.backup();let changed=0;this.store.db.exec('BEGIN');try{for(const id of new Set(ids)){if(this.busy.has(id))throw Error('记录正在采集，请稍后清理');const row=this.store.get('inbox',id);if(row){this.store.put('inbox',{...row,deletedAt:action==='trash'?new Date().toISOString():null});changed++;}}this.store.db.exec('COMMIT');return {changed};}catch(e){this.store.db.exec('ROLLBACK');throw e;}}
  async capture(url){const id=xId(url),old=this.store.get('inbox',id);if(old)return old.deletedAt?this.store.put('inbox',{...old,deletedAt:null}):old;if(this.busy.has(id))throw Error('该帖子正在读取');this.busy.add(id);try{const r=await this.fetcher('https://api.fxtwitter.com/2/thread/'+id,{redirect:'error',signal:AbortSignal.timeout(15000),headers:{'User-Agent':'PromptWorkbench/0.3'}});if(!r.ok)throw Error('原帖接口暂不可用');let bytes=0,text='';const decoder=new TextDecoder();for await(const c of r.body){bytes+=c.length;if(bytes>2e6)throw Error('线程内容超过2MB');text+=decoder.decode(c,{stream:true});}const d=JSON.parse(text+decoder.decode());if(d.code!==200||!d.status?.text)throw Error('帖子不存在或不可读取');const raw=[d.status,...(d.thread||[])],seen=new Set(),posts=[];for(const p of raw.slice(0,31)){if(!/^\d{10,25}$/.test(String(p.id))||typeof p.text!=='string'||seen.has(p.id))continue;seen.add(p.id);const author=String(p.author?.screen_name||'');posts.push({id:String(p.id),text:p.text.slice(0,60000),author,sourceUrl:'https://x.com/'+(author||'i')+'/status/'+p.id,sameAuthor:!!author&&author===d.status.author?.screen_name,images:(p.media?.photos||[]).slice(0,4).map(m=>coverUrl(m.url)).filter(Boolean)});}const candidate=[...posts].filter(p=>p.sameAuthor&&p.id!==id).sort((a,b)=>b.text.length-a.text.length)[0]||posts[0];return this.store.put('inbox',{id,url:'https://x.com/'+d.status.author.screen_name+'/status/'+id,author:d.status.author.screen_name,posts,candidateId:candidate?.id,status:'pending',capturedAt:new Date().toISOString(),warning:'候选文本需人工确认；读取结果不保证线程完整。'});}catch(e){throw Error('X读取失败：'+(e.message==='fetch failed'?'网络连接不可用':e.message));}finally{this.busy.delete(id);}}
  collect(id,b){const item=this.store.get('inbox',id);if(!item||item.deletedAt)throw Error('收件箱记录不存在或在回收站');if(item.assetId&&this.store.get('assets',item.assetId)){const old=this.store.get('assets',item.assetId);if(old.deletedAt){this.store.backup();return this.store.put('assets',{...old,deletedAt:null});}return old;}const post=item.posts.find(p=>p.id===b.postId);if(!post)throw Error('请选择具体帖子');this.store.backup();this.store.db.exec('BEGIN IMMEDIATE');try{const a=saveAsset(this.store,{title:b.title,content:b.content,category:'X原帖收藏',note:'来自具体帖子，经用户确认/整理；未经原作者开放授权，请核对正文及参考条件。',source:{sourceId:'x-direct',originId:post.id,url:post.sourceUrl,author:post.author,license:'未声明开放许可 · 原作者保留权利'}});this.store.put('inbox',{...item,status:'collected',assetId:a.id,selectedPostId:post.id});this.store.db.exec('COMMIT');return a;}catch(e){this.store.db.exec('ROLLBACK');throw e;}}
}
